/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.intlflight.ordering.contract.commontype.v1;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 票台信息
 */
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AgencyType", namespace = "urn:com:ctrip:flight:intl:booking:order:contract:commontype:v1", propOrder = {
    "agencyID",
    "agencyCode",
    "cityID",
    "cityCode",
    "agencyName",
    "officialName"
})
@SuppressWarnings("all")
public class AgencyType implements Serializable {

    private static final long serialVersionUID = 1L;

    public AgencyType(
        int agencyID, 
        String agencyCode, 
        int cityID, 
        String cityCode, 
        String agencyName, 
        String officialName) {
        this.agencyID = agencyID;
        this.agencyCode = agencyCode;
        this.cityID = cityID;
        this.cityCode = cityCode;
        this.agencyName = agencyName;
        this.officialName = officialName;
    }

    public AgencyType() {
    }

    @JsonProperty("AgencyID")
    @XmlElement(name = "AgencyID")
    private int agencyID;

    @JsonProperty("AgencyCode")
    @XmlElement(name = "AgencyCode")
    private String agencyCode;

    @JsonProperty("CityID")
    @XmlElement(name = "CityID")
    private int cityID;

    @JsonProperty("CityCode")
    @XmlElement(name = "CityCode")
    private String cityCode;

    @JsonProperty("AgencyName")
    @XmlElement(name = "AgencyName")
    private String agencyName;

    @JsonProperty("OfficialName")
    @XmlElement(name = "OfficialName")
    private String officialName;

    /**
     * *票台ID
     */
    public int getAgencyID() {
        return this.agencyID;
    }

    public void setAgencyID(int agencyID) {
        this.agencyID = agencyID;
    }

    /**
     * *票台代码
     */
    public String getAgencyCode() {
        return this.agencyCode;
    }

    public void setAgencyCode(String agencyCode) {
        this.agencyCode = agencyCode;
    }

    /**
     * 城市ID
     */
    public int getCityID() {
        return this.cityID;
    }

    public void setCityID(int cityID) {
        this.cityID = cityID;
    }

    /**
     * 城市代码
     */
    public String getCityCode() {
        return this.cityCode;
    }

    public void setCityCode(String cityCode) {
        this.cityCode = cityCode;
    }

    /**
     * 供应商名称
     */
    public String getAgencyName() {
        return this.agencyName;
    }

    public void setAgencyName(String agencyName) {
        this.agencyName = agencyName;
    }

    /**
     * 供应商航协认可的名称
     */
    public String getOfficialName() {
        return this.officialName;
    }

    public void setOfficialName(String officialName) {
        this.officialName = officialName;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final AgencyType other = (AgencyType)obj;
        return
            Objects.equal(this.agencyID, other.agencyID) && 
            Objects.equal(this.agencyCode, other.agencyCode) && 
            Objects.equal(this.cityID, other.cityID) && 
            Objects.equal(this.cityCode, other.cityCode) && 
            Objects.equal(this.agencyName, other.agencyName) && 
            Objects.equal(this.officialName, other.officialName);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.agencyID);
        result = 31 * result + Objects.hashCode(this.agencyCode);
        result = 31 * result + Objects.hashCode(this.cityID);
        result = 31 * result + Objects.hashCode(this.cityCode);
        result = 31 * result + Objects.hashCode(this.agencyName);
        result = 31 * result + Objects.hashCode(this.officialName);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("agencyID", agencyID)
            .add("agencyCode", agencyCode)
            .add("cityID", cityID)
            .add("cityCode", cityCode)
            .add("agencyName", agencyName)
            .add("officialName", officialName)
            .toString();
    }

}