/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.intlflight.ordering.contract.commontype.v1;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.io.Serializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 商旅信息
 */
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CorpMiscInfoType", namespace = "urn:com:ctrip:flight:intl:booking:order:contract:commontype:v1", propOrder = {
    "corpID",
    "serviceFee"
})
@SuppressWarnings("all")
public class CorpMiscInfoType implements Serializable {

    private static final long serialVersionUID = 1L;

    public CorpMiscInfoType(
        String corpID, 
        BigDecimal serviceFee) {
        this.corpID = corpID;
        this.serviceFee = serviceFee;
    }

    public CorpMiscInfoType() {
        this.serviceFee = new BigDecimal(0);
    }

    @JsonProperty("CorpID")
    @XmlElement(name = "CorpID")
    private String corpID;

    @JsonProperty("ServiceFee")
    @XmlElement(name = "ServiceFee")
    private BigDecimal serviceFee;

    /**
     * 商旅ID
     */
    public String getCorpID() {
        return this.corpID;
    }

    public void setCorpID(String corpID) {
        this.corpID = corpID;
    }

    /**
     * 商旅用户服务费
     */
    public BigDecimal getServiceFee() {
        return this.serviceFee;
    }

    public void setServiceFee(BigDecimal serviceFee) {
        this.serviceFee = serviceFee;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final CorpMiscInfoType other = (CorpMiscInfoType)obj;
        return
            Objects.equal(this.corpID, other.corpID) && 
            Objects.equal(this.serviceFee, other.serviceFee);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.corpID);
        result = 31 * result + Objects.hashCode(this.serviceFee);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("corpID", corpID)
            .add("serviceFee", serviceFee)
            .toString();
    }

}