/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.intlflight.ordering.contract.commontype.v1;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 错误信息
 */
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ErrorResultType", namespace = "urn:com:ctrip:flight:intl:booking:order:contract:commontype:v1", propOrder = {
    "errorCode",
    "errorDesc"
})
@SuppressWarnings("all")
public class ErrorResultType implements Serializable {

    private static final long serialVersionUID = 1L;

    public ErrorResultType(
        int errorCode, 
        String errorDesc) {
        this.errorCode = errorCode;
        this.errorDesc = errorDesc;
    }

    public ErrorResultType() {
    }

    @JsonProperty("ErrorCode")
    @XmlElement(name = "ErrorCode")
    private int errorCode;

    @JsonProperty("ErrorDesc")
    @XmlElement(name = "ErrorDesc")
    private String errorDesc;

    /**
     * 整型错误码有助于客户端编写错误处理代码
     */
    public int getErrorCode() {
        return this.errorCode;
    }

    public void setErrorCode(int errorCode) {
        this.errorCode = errorCode;
    }

    /**
     * 描述字串有助于理解错误内容，也用于把错误信息传递给最终用户
     */
    public String getErrorDesc() {
        return this.errorDesc;
    }

    public void setErrorDesc(String errorDesc) {
        this.errorDesc = errorDesc;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final ErrorResultType other = (ErrorResultType)obj;
        return
            Objects.equal(this.errorCode, other.errorCode) && 
            Objects.equal(this.errorDesc, other.errorDesc);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.errorCode);
        result = 31 * result + Objects.hashCode(this.errorDesc);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("errorCode", errorCode)
            .add("errorDesc", errorDesc)
            .toString();
    }

}