/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.intlflight.ordering.contract.commontype.v1;

import com.ctrip.intlflight.ordering.contract.saveorder.v2.IDCardExtType;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.io.Serializable;
import java.util.Calendar;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * 身份证件相关信息
 */
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlSeeAlso({
    IDCardExtType.class
})
@XmlType(name = "IDCardInfoType", namespace = "urn:com:ctrip:flight:intl:booking:order:contract:commontype:v1", propOrder = {
    "idCardType",
    "idCardNo",
    "cardTimeLimit"
})
@SuppressWarnings("all")
public class IDCardInfoType implements Serializable {

    private static final long serialVersionUID = 1L;

    public IDCardInfoType(
        String idCardType, 
        String idCardNo, 
        Calendar cardTimeLimit) {
        this.idCardType = idCardType;
        this.idCardNo = idCardNo;
        this.cardTimeLimit = cardTimeLimit;
    }

    public IDCardInfoType() {
        this.cardTimeLimit = new java.util.GregorianCalendar(1, Calendar.JANUARY, 1, 0, 0, 0);
        this.cardTimeLimit.setTimeZone(sun.util.calendar.ZoneInfo.getTimeZone("UTC"));
    }

    @JsonProperty("IDCardType")
    @XmlElement(name = "IDCardType")
    private String idCardType;

    @JsonProperty("IDCardNo")
    @XmlElement(name = "IDCardNo")
    private String idCardNo;

    @JsonProperty("CardTimeLimit")
    @XmlElement(name = "CardTimeLimit")
    private Calendar cardTimeLimit;

    /**
     * *证件类型
     */
    public String getIdCardType() {
        return this.idCardType;
    }

    public void setIdCardType(String idCardType) {
        this.idCardType = idCardType;
    }

    /**
     * *证件号
     */
    public String getIdCardNo() {
        return this.idCardNo;
    }

    public void setIdCardNo(String idCardNo) {
        this.idCardNo = idCardNo;
    }

    /**
     * 证件有效期
     */
    public Calendar getCardTimeLimit() {
        return this.cardTimeLimit;
    }

    public void setCardTimeLimit(Calendar cardTimeLimit) {
        this.cardTimeLimit = cardTimeLimit;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final IDCardInfoType other = (IDCardInfoType)obj;
        return
            Objects.equal(this.idCardType, other.idCardType) && 
            Objects.equal(this.idCardNo, other.idCardNo) && 
            Objects.equal(this.cardTimeLimit, other.cardTimeLimit);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.idCardType);
        result = 31 * result + Objects.hashCode(this.idCardNo);
        result = 31 * result + Objects.hashCode(this.cardTimeLimit);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("idCardType", idCardType)
            .add("idCardNo", idCardNo)
            .add("cardTimeLimit", cardTimeLimit)
            .toString();
    }

}