/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
@XmlSchema(namespace = "urn:com:ctrip:flight:intl:booking:order:contract:commontype:v1", elementFormDefault = XmlNsForm.QUALIFIED)
package com.ctrip.intlflight.ordering.contract.commontype.v1;

import javax.xml.bind.annotation.XmlNsForm;
import javax.xml.bind.annotation.XmlSchema;
