/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.intlflight.ordering.contract.commontype.v1;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 乘客限制
 */
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PassengerRestrictionType", namespace = "urn:com:ctrip:flight:intl:booking:order:contract:commontype:v1", propOrder = {
    "minPassengerCount",
    "maxPassengerCount",
    "nationalityInclude",
    "nationalityExclude",
    "nationalityIncludeCN",
    "nationalityExcludeCN",
    "maxAgeLimitition",
    "minAgeLimitition"
})
@SuppressWarnings("all")
public class PassengerRestrictionType implements Serializable {

    private static final long serialVersionUID = 1L;

    public PassengerRestrictionType(
        int minPassengerCount, 
        int maxPassengerCount, 
        String nationalityInclude, 
        String nationalityExclude, 
        String nationalityIncludeCN, 
        String nationalityExcludeCN, 
        int maxAgeLimitition, 
        int minAgeLimitition) {
        this.minPassengerCount = minPassengerCount;
        this.maxPassengerCount = maxPassengerCount;
        this.nationalityInclude = nationalityInclude;
        this.nationalityExclude = nationalityExclude;
        this.nationalityIncludeCN = nationalityIncludeCN;
        this.nationalityExcludeCN = nationalityExcludeCN;
        this.maxAgeLimitition = maxAgeLimitition;
        this.minAgeLimitition = minAgeLimitition;
    }

    public PassengerRestrictionType() {
    }

    @JsonProperty("MinPassengerCount")
    @XmlElement(name = "MinPassengerCount")
    private int minPassengerCount;

    @JsonProperty("MaxPassengerCount")
    @XmlElement(name = "MaxPassengerCount")
    private int maxPassengerCount;

    @JsonProperty("NationalityInclude")
    @XmlElement(name = "NationalityInclude")
    private String nationalityInclude;

    @JsonProperty("NationalityExclude")
    @XmlElement(name = "NationalityExclude")
    private String nationalityExclude;

    @JsonProperty("NationalityIncludeCN")
    @XmlElement(name = "NationalityIncludeCN")
    private String nationalityIncludeCN;

    @JsonProperty("NationalityExcludeCN")
    @XmlElement(name = "NationalityExcludeCN")
    private String nationalityExcludeCN;

    @JsonProperty("MaxAgeLimitition")
    @XmlElement(name = "MaxAgeLimitition")
    private int maxAgeLimitition;

    @JsonProperty("MinAgeLimitition")
    @XmlElement(name = "MinAgeLimitition")
    private int minAgeLimitition;

    public int getMinPassengerCount() {
        return this.minPassengerCount;
    }

    public void setMinPassengerCount(int minPassengerCount) {
        this.minPassengerCount = minPassengerCount;
    }

    public int getMaxPassengerCount() {
        return this.maxPassengerCount;
    }

    public void setMaxPassengerCount(int maxPassengerCount) {
        this.maxPassengerCount = maxPassengerCount;
    }

    public String getNationalityInclude() {
        return this.nationalityInclude;
    }

    public void setNationalityInclude(String nationalityInclude) {
        this.nationalityInclude = nationalityInclude;
    }

    public String getNationalityExclude() {
        return this.nationalityExclude;
    }

    public void setNationalityExclude(String nationalityExclude) {
        this.nationalityExclude = nationalityExclude;
    }

    public String getNationalityIncludeCN() {
        return this.nationalityIncludeCN;
    }

    public void setNationalityIncludeCN(String nationalityIncludeCN) {
        this.nationalityIncludeCN = nationalityIncludeCN;
    }

    public String getNationalityExcludeCN() {
        return this.nationalityExcludeCN;
    }

    public void setNationalityExcludeCN(String nationalityExcludeCN) {
        this.nationalityExcludeCN = nationalityExcludeCN;
    }

    public int getMaxAgeLimitition() {
        return this.maxAgeLimitition;
    }

    public void setMaxAgeLimitition(int maxAgeLimitition) {
        this.maxAgeLimitition = maxAgeLimitition;
    }

    public int getMinAgeLimitition() {
        return this.minAgeLimitition;
    }

    public void setMinAgeLimitition(int minAgeLimitition) {
        this.minAgeLimitition = minAgeLimitition;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final PassengerRestrictionType other = (PassengerRestrictionType)obj;
        return
            Objects.equal(this.minPassengerCount, other.minPassengerCount) && 
            Objects.equal(this.maxPassengerCount, other.maxPassengerCount) && 
            Objects.equal(this.nationalityInclude, other.nationalityInclude) && 
            Objects.equal(this.nationalityExclude, other.nationalityExclude) && 
            Objects.equal(this.nationalityIncludeCN, other.nationalityIncludeCN) && 
            Objects.equal(this.nationalityExcludeCN, other.nationalityExcludeCN) && 
            Objects.equal(this.maxAgeLimitition, other.maxAgeLimitition) && 
            Objects.equal(this.minAgeLimitition, other.minAgeLimitition);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.minPassengerCount);
        result = 31 * result + Objects.hashCode(this.maxPassengerCount);
        result = 31 * result + Objects.hashCode(this.nationalityInclude);
        result = 31 * result + Objects.hashCode(this.nationalityExclude);
        result = 31 * result + Objects.hashCode(this.nationalityIncludeCN);
        result = 31 * result + Objects.hashCode(this.nationalityExcludeCN);
        result = 31 * result + Objects.hashCode(this.maxAgeLimitition);
        result = 31 * result + Objects.hashCode(this.minAgeLimitition);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("minPassengerCount", minPassengerCount)
            .add("maxPassengerCount", maxPassengerCount)
            .add("nationalityInclude", nationalityInclude)
            .add("nationalityExclude", nationalityExclude)
            .add("nationalityIncludeCN", nationalityIncludeCN)
            .add("nationalityExcludeCN", nationalityExcludeCN)
            .add("maxAgeLimitition", maxAgeLimitition)
            .add("minAgeLimitition", minAgeLimitition)
            .toString();
    }

}