/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.intlflight.ordering.contract.commontype.v1;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.io.Serializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 基础价格
 */
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PriceDetailType", namespace = "urn:com:ctrip:flight:intl:booking:order:contract:commontype:v1", propOrder = {
    "currency",
    "salePrice",
    "tax",
    "publishPrice",
    "accountPrice",
    "netPrice"
})
@SuppressWarnings("all")
public class PriceDetailType implements Serializable {

    private static final long serialVersionUID = 1L;

    public PriceDetailType(
        String currency, 
        BigDecimal salePrice, 
        BigDecimal tax, 
        BigDecimal publishPrice, 
        BigDecimal accountPrice, 
        BigDecimal netPrice) {
        this.currency = currency;
        this.salePrice = salePrice;
        this.tax = tax;
        this.publishPrice = publishPrice;
        this.accountPrice = accountPrice;
        this.netPrice = netPrice;
    }

    public PriceDetailType() {
        this.salePrice = new BigDecimal(0);
        this.tax = new BigDecimal(0);
        this.publishPrice = new BigDecimal(0);
        this.accountPrice = new BigDecimal(0);
        this.netPrice = new BigDecimal(0);
    }

    @JsonProperty("Currency")
    @XmlElement(name = "Currency")
    private String currency;

    @JsonProperty("SalePrice")
    @XmlElement(name = "SalePrice")
    private BigDecimal salePrice;

    @JsonProperty("Tax")
    @XmlElement(name = "Tax")
    private BigDecimal tax;

    @JsonProperty("PublishPrice")
    @XmlElement(name = "PublishPrice")
    private BigDecimal publishPrice;

    @JsonProperty("AccountPrice")
    @XmlElement(name = "AccountPrice")
    private BigDecimal accountPrice;

    @JsonProperty("NetPrice")
    @XmlElement(name = "NetPrice")
    private BigDecimal netPrice;

    /**
     * *币种
     */
    public String getCurrency() {
        return this.currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * *携程卖价
     */
    public BigDecimal getSalePrice() {
        return this.salePrice;
    }

    public void setSalePrice(BigDecimal salePrice) {
        this.salePrice = salePrice;
    }

    /**
     * *税费
     */
    public BigDecimal getTax() {
        return this.tax;
    }

    public void setTax(BigDecimal tax) {
        this.tax = tax;
    }

    /**
     * *航空公司卖价(含附加费)，列表查询不输出
     */
    public BigDecimal getPublishPrice() {
        return this.publishPrice;
    }

    public void setPublishPrice(BigDecimal publishPrice) {
        this.publishPrice = publishPrice;
    }

    /**
     * *航空公司结算价，列表查询不输出
     */
    public BigDecimal getAccountPrice() {
        return this.accountPrice;
    }

    public void setAccountPrice(BigDecimal accountPrice) {
        this.accountPrice = accountPrice;
    }

    /**
     * 中间变量低价（包含后返），列表查询不输出
     */
    public BigDecimal getNetPrice() {
        return this.netPrice;
    }

    public void setNetPrice(BigDecimal netPrice) {
        this.netPrice = netPrice;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final PriceDetailType other = (PriceDetailType)obj;
        return
            Objects.equal(this.currency, other.currency) && 
            Objects.equal(this.salePrice, other.salePrice) && 
            Objects.equal(this.tax, other.tax) && 
            Objects.equal(this.publishPrice, other.publishPrice) && 
            Objects.equal(this.accountPrice, other.accountPrice) && 
            Objects.equal(this.netPrice, other.netPrice);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.currency);
        result = 31 * result + Objects.hashCode(this.salePrice);
        result = 31 * result + Objects.hashCode(this.tax);
        result = 31 * result + Objects.hashCode(this.publishPrice);
        result = 31 * result + Objects.hashCode(this.accountPrice);
        result = 31 * result + Objects.hashCode(this.netPrice);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("currency", currency)
            .add("salePrice", salePrice)
            .add("tax", tax)
            .add("publishPrice", publishPrice)
            .add("accountPrice", accountPrice)
            .add("netPrice", netPrice)
            .toString();
    }

}