/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.intlflight.ordering.contract.commontype.v1;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.io.Serializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TicketingTimeLimitType", namespace = "urn:com:ctrip:flight:intl:booking:order:contract:commontype:v1", propOrder = {
    "timeLimitType",
    "limitTime",
    "averageTicketingTime"
})
@SuppressWarnings("all")
public class TicketingTimeLimitType implements Serializable {

    private static final long serialVersionUID = 1L;

    public TicketingTimeLimitType(
        int timeLimitType, 
        int limitTime, 
        BigDecimal averageTicketingTime) {
        this.timeLimitType = timeLimitType;
        this.limitTime = limitTime;
        this.averageTicketingTime = averageTicketingTime;
    }

    public TicketingTimeLimitType() {
        this.averageTicketingTime = new BigDecimal(0);
    }

    @JsonProperty("TimeLimitType")
    @XmlElement(name = "TimeLimitType")
    private int timeLimitType;

    @JsonProperty("LimitTime")
    @XmlElement(name = "LimitTime")
    private int limitTime;

    @JsonProperty("AverageTicketingTime")
    @XmlElement(name = "AverageTicketingTime")
    private BigDecimal averageTicketingTime;

    /**
     * 出票保护时限类型，0:订单生成出票单后,1:航班起飞时间前
     */
    public int getTimeLimitType() {
        return this.timeLimitType;
    }

    public void setTimeLimitType(int timeLimitType) {
        this.timeLimitType = timeLimitType;
    }

    /**
     * 出票保护时限，单位分钟
     */
    public int getLimitTime() {
        return this.limitTime;
    }

    public void setLimitTime(int limitTime) {
        this.limitTime = limitTime;
    }

    /**
     * 平均出票时间，单位为分钟
     */
    public BigDecimal getAverageTicketingTime() {
        return this.averageTicketingTime;
    }

    public void setAverageTicketingTime(BigDecimal averageTicketingTime) {
        this.averageTicketingTime = averageTicketingTime;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final TicketingTimeLimitType other = (TicketingTimeLimitType)obj;
        return
            Objects.equal(this.timeLimitType, other.timeLimitType) && 
            Objects.equal(this.limitTime, other.limitTime) && 
            Objects.equal(this.averageTicketingTime, other.averageTicketingTime);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.timeLimitType);
        result = 31 * result + Objects.hashCode(this.limitTime);
        result = 31 * result + Objects.hashCode(this.averageTicketingTime);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("timeLimitType", timeLimitType)
            .add("limitTime", limitTime)
            .add("averageTicketingTime", averageTicketingTime)
            .toString();
    }

}