// Generated by eBay Common SDK Platform
package com.ctrip.intlflight.ordering.contract.saveorder.v2;

import com.fasterxml.jackson.annotation.JsonValue;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlEnumValue;

/**
 * 请求模式类型
 */
@XmlType(name = "ActionType")
@XmlEnum
@SuppressWarnings("all")
public enum ActionType {

    /**
     * 创建未提交订单
     */
    @XmlEnumValue("CreateOrder")
    CreateOrder(0, "CreateOrder"),

    /**
     * 修改未提交或下一步回退订单
     */
    @XmlEnumValue("ModifyOrder")
    ModifyOrder(1, "ModifyOrder"),

    /**
     * 提交未提交订单或对已提交暂缓订单改立即
     */
    @XmlEnumValue("SubmitOrder")
    SubmitOrder(2, "SubmitOrder");

    private final int intValue;
    private final String value;

    ActionType(int intValue, String value) {
        this.intValue = intValue;
        this.value = value;
    }

    public int getValue() {
        return intValue;
    }

    @JsonValue
    public String value() {
        return value;
    }

    public static ActionType fromValue(String v) {
        for (ActionType e: ActionType.values()) {
            if (e.value.equalsIgnoreCase(v)) {
                return e;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public static ActionType findByValue(int value) {
        switch (value) {
            case 0:
                return CreateOrder;
            case 1:
                return ModifyOrder;
            case 2:
                return SubmitOrder;
            default:
                return null;
        }
    }
}