/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.intlflight.ordering.contract.saveorder.v2;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 联系人备注类型
 */
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContactRemarkType", namespace = "urn:com:ctrip:flight:intl:booking:order:contract:saveorder:v2", propOrder = {
    "needHotel",
    "needMoreBagage",
    "trackIDCard"
})
@SuppressWarnings("all")
public class ContactRemarkType implements Serializable {

    private static final long serialVersionUID = 1L;

    public ContactRemarkType(
        boolean needHotel, 
        boolean needMoreBagage, 
        boolean trackIDCard) {
        this.needHotel = needHotel;
        this.needMoreBagage = needMoreBagage;
        this.trackIDCard = trackIDCard;
    }

    public ContactRemarkType() {
    }

    @JsonProperty("NeedHotel")
    @XmlElement(name = "NeedHotel")
    private boolean needHotel;

    @JsonProperty("NeedMoreBagage")
    @XmlElement(name = "NeedMoreBagage")
    private boolean needMoreBagage;

    @JsonProperty("TrackIDCard")
    @XmlElement(name = "TrackIDCard")
    private boolean trackIDCard;

    /**
     * 需申请酒店
     */
    public boolean getNeedHotel() {
        return this.needHotel;
    }

    public void setNeedHotel(boolean needHotel) {
        this.needHotel = needHotel;
    }

    /**
     * 需申请额外行李额
     */
    public boolean getNeedMoreBagage() {
        return this.needMoreBagage;
    }

    public void setNeedMoreBagage(boolean needMoreBagage) {
        this.needMoreBagage = needMoreBagage;
    }

    /**
     * 跟踪证件
     */
    public boolean getTrackIDCard() {
        return this.trackIDCard;
    }

    public void setTrackIDCard(boolean trackIDCard) {
        this.trackIDCard = trackIDCard;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final ContactRemarkType other = (ContactRemarkType)obj;
        return
            Objects.equal(this.needHotel, other.needHotel) && 
            Objects.equal(this.needMoreBagage, other.needMoreBagage) && 
            Objects.equal(this.trackIDCard, other.trackIDCard);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.needHotel);
        result = 31 * result + Objects.hashCode(this.needMoreBagage);
        result = 31 * result + Objects.hashCode(this.trackIDCard);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("needHotel", needHotel)
            .add("needMoreBagage", needMoreBagage)
            .add("trackIDCard", trackIDCard)
            .toString();
    }

}