/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.intlflight.ordering.contract.saveorder.v2;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.io.Serializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 优惠券：金额和比率为二选一，同时只能有一个且必须有一个被填充。
 */
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CouponType", namespace = "urn:com:ctrip:flight:intl:booking:order:contract:saveorder:v2", propOrder = {
    "couponID",
    "discountRuleID",
    "amount",
    "discountRate"
})
@SuppressWarnings("all")
public class CouponType implements Serializable {

    private static final long serialVersionUID = 1L;

    public CouponType(
        String couponID, 
        int discountRuleID, 
        BigDecimal amount, 
        BigDecimal discountRate) {
        this.couponID = couponID;
        this.discountRuleID = discountRuleID;
        this.amount = amount;
        this.discountRate = discountRate;
    }

    public CouponType() {
    }

    @JsonProperty("CouponID")
    @XmlElement(name = "CouponID")
    private String couponID;

    @JsonProperty("DiscountRuleID")
    @XmlElement(name = "DiscountRuleID")
    private int discountRuleID;

    @JsonProperty("Amount")
    @XmlElement(name = "Amount", nillable = true)
    private BigDecimal amount;

    @JsonProperty("DiscountRate")
    @XmlElement(name = "DiscountRate", nillable = true)
    private BigDecimal discountRate;

    /**
     * 优惠券代码
     */
    public String getCouponID() {
        return this.couponID;
    }

    public void setCouponID(String couponID) {
        this.couponID = couponID;
    }

    /**
     * 优惠规则代码
     */
    public int getDiscountRuleID() {
        return this.discountRuleID;
    }

    public void setDiscountRuleID(int discountRuleID) {
        this.discountRuleID = discountRuleID;
    }

    /**
     * 优惠券金额
     */
    public BigDecimal getAmount() {
        return this.amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * 优惠比率
     */
    public BigDecimal getDiscountRate() {
        return this.discountRate;
    }

    public void setDiscountRate(BigDecimal discountRate) {
        this.discountRate = discountRate;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final CouponType other = (CouponType)obj;
        return
            Objects.equal(this.couponID, other.couponID) && 
            Objects.equal(this.discountRuleID, other.discountRuleID) && 
            Objects.equal(this.amount, other.amount) && 
            Objects.equal(this.discountRate, other.discountRate);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.couponID);
        result = 31 * result + Objects.hashCode(this.discountRuleID);
        result = 31 * result + Objects.hashCode(this.amount);
        result = 31 * result + Objects.hashCode(this.discountRate);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("couponID", couponID)
            .add("discountRuleID", discountRuleID)
            .add("amount", amount)
            .add("discountRate", discountRate)
            .toString();
    }

}