/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.intlflight.ordering.contract.saveorder.v2;

import com.ctrip.intlflight.ordering.contract.commontype.v1.IDCardInfoType;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 证件相关信息（适应多证件类型）
 */
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IDCardExtType", namespace = "urn:com:ctrip:flight:intl:booking:order:contract:saveorder:v2", propOrder = {
    "puIndexes",
    "personName"
})
@SuppressWarnings("all")
public class IDCardExtType extends IDCardInfoType implements Serializable {

    private static final long serialVersionUID = 1L;

    public IDCardExtType(
        String puIndexes, 
        String personName) {
        this.puIndexes = puIndexes;
        this.personName = personName;
    }

    public IDCardExtType() {
    }

    @JsonProperty("PUIndexes")
    @XmlElement(name = "PUIndexes")
    private String puIndexes;

    @JsonProperty("PersonName")
    @XmlElement(name = "PersonName")
    private String personName;

    /**
     * *PriceUnit索引
     */
    public String getPuIndexes() {
        return this.puIndexes;
    }

    public void setPuIndexes(String puIndexes) {
        this.puIndexes = puIndexes;
    }

    /**
     * 乘机人姓名
     */
    public String getPersonName() {
        return this.personName;
    }

    public void setPersonName(String personName) {
        this.personName = personName;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final IDCardExtType other = (IDCardExtType)obj;
        return
            Objects.equal(this.puIndexes, other.puIndexes) && 
            Objects.equal(this.personName, other.personName);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.puIndexes);
        result = 31 * result + Objects.hashCode(this.personName);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("puIndexes", puIndexes)
            .add("personName", personName)
            .toString();
    }

}