/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.intlflight.ordering.contract.saveorder.v2;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 保险产品信息
 */
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InsuranceProductInfoType", namespace = "urn:com:ctrip:flight:intl:booking:order:contract:saveorder:v2", propOrder = {
    "flightWay",
    "policyChannel",
    "age",
    "policyHolder"
})
@SuppressWarnings("all")
public class InsuranceProductInfoType implements Serializable {

    private static final long serialVersionUID = 1L;

    public InsuranceProductInfoType(
        String flightWay, 
        String policyChannel, 
        int age, 
        PolicyHolderType policyHolder) {
        this.flightWay = flightWay;
        this.policyChannel = policyChannel;
        this.age = age;
        this.policyHolder = policyHolder;
    }

    public InsuranceProductInfoType() {
    }

    @JsonProperty("FlightWay")
    @XmlElement(name = "FlightWay")
    private String flightWay;

    @JsonProperty("PolicyChannel")
    @XmlElement(name = "PolicyChannel")
    private String policyChannel;

    @JsonProperty("Age")
    @XmlElement(name = "Age")
    private int age;

    @JsonProperty("PolicyHolder")
    @XmlElement(name = "PolicyHolder")
    private PolicyHolderType policyHolder;

    /**
     * 航程类型，下单用以判断是按订单投保还是按航段投保
     */
    public String getFlightWay() {
        return this.flightWay;
    }

    public void setFlightWay(String flightWay) {
        this.flightWay = flightWay;
    }

    /**
     * 可售政策的渠道
     */
    public String getPolicyChannel() {
        return this.policyChannel;
    }

    public void setPolicyChannel(String policyChannel) {
        this.policyChannel = policyChannel;
    }

    /**
     * 购买乘客年龄
     */
    public int getAge() {
        return this.age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    /**
     * 投保人信息
     */
    public PolicyHolderType getPolicyHolder() {
        return this.policyHolder;
    }

    public void setPolicyHolder(PolicyHolderType policyHolder) {
        this.policyHolder = policyHolder;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final InsuranceProductInfoType other = (InsuranceProductInfoType)obj;
        return
            Objects.equal(this.flightWay, other.flightWay) && 
            Objects.equal(this.policyChannel, other.policyChannel) && 
            Objects.equal(this.age, other.age) && 
            Objects.equal(this.policyHolder, other.policyHolder);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.flightWay);
        result = 31 * result + Objects.hashCode(this.policyChannel);
        result = 31 * result + Objects.hashCode(this.age);
        result = 31 * result + Objects.hashCode(this.policyHolder);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("flightWay", flightWay)
            .add("policyChannel", policyChannel)
            .add("age", age)
            .add("policyHolder", policyHolder)
            .toString();
    }

}