/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.intlflight.ordering.contract.saveorder.v2;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 *         Offline接入所需要信息
 *       
 */
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OfflineMiscInfoType", namespace = "urn:com:ctrip:flight:intl:booking:order:contract:saveorder:v2", propOrder = {
    "contactRemark",
    "operatorInfo",
    "postponeFee",
    "descInfo",
    "salesTypeInfo",
    "sendTicketCity",
    "needPayDelay",
    "isManual",
    "needPrintTicket"
})
@SuppressWarnings("all")
public class OfflineMiscInfoType implements Serializable {

    private static final long serialVersionUID = 1L;

    public OfflineMiscInfoType(
        ContactRemarkType contactRemark, 
        OperatorInfoType operatorInfo,
        PostponeFeeType postponeFee,
        DescInfoType descInfo, 
        SalesTypeInfoType salesTypeInfo,
        int sendTicketCity, 
        boolean needPayDelay, 
        boolean isManual, 
        boolean needPrintTicket) {
        this.contactRemark = contactRemark;
        this.operatorInfo = operatorInfo;
        this.postponeFee = postponeFee;
        this.descInfo = descInfo;
        this.salesTypeInfo = salesTypeInfo;
        this.sendTicketCity = sendTicketCity;
        this.needPayDelay = needPayDelay;
        this.isManual = isManual;
        this.needPrintTicket = needPrintTicket;
    }

    public OfflineMiscInfoType() {
    }

    @JsonProperty("ContactRemark")
    @XmlElement(name = "ContactRemark")
    private ContactRemarkType contactRemark;

    @JsonProperty("OperatorInfo")
    @XmlElement(name = "OperatorInfo")
    private OperatorInfoType operatorInfo;

    @JsonProperty("PostponeFee")
    @XmlElement(name = "PostponeFee")
    private PostponeFeeType postponeFee;

    @JsonProperty("DescInfo")
    @XmlElement(name = "DescInfo")
    private DescInfoType descInfo;

    @JsonProperty("SalesTypeInfo")
    @XmlElement(name = "SalesTypeInfo")
    private SalesTypeInfoType salesTypeInfo;

    @JsonProperty("SendTicketCity")
    @XmlElement(name = "SendTicketCity")
    private int sendTicketCity;

    @JsonProperty("NeedPayDelay")
    @XmlElement(name = "NeedPayDelay")
    private boolean needPayDelay;

    @JsonProperty("IsManual")
    @XmlElement(name = "IsManual")
    private boolean isManual;

    @JsonProperty("NeedPrintTicket")
    @XmlElement(name = "NeedPrintTicket")
    private boolean needPrintTicket;

    /**
     * 联系人备注信息
     */
    public ContactRemarkType getContactRemark() {
        return this.contactRemark;
    }

    public void setContactRemark(ContactRemarkType contactRemark) {
        this.contactRemark = contactRemark;
    }

    /**
     * 操作人信息
     */
    public OperatorInfoType getOperatorInfo() {
        return this.operatorInfo;
    }

    public void setOperatorInfo(OperatorInfoType operatorInfo) {
        this.operatorInfo = operatorInfo;
    }

    /**
     * 改期收费信息
     */
    public PostponeFeeType getPostponeFee() {
        return this.postponeFee;
    }

    public void setPostponeFee(PostponeFeeType postponeFee) {
        this.postponeFee = postponeFee;
    }

    /**
     * 备注信息
     */
    public DescInfoType getDescInfo() {
        return this.descInfo;
    }

    public void setDescInfo(DescInfoType descInfo) {
        this.descInfo = descInfo;
    }

    /**
     * 渠道信息
     */
    public SalesTypeInfoType getSalesTypeInfo() {
        return this.salesTypeInfo;
    }

    public void setSalesTypeInfo(SalesTypeInfoType salesTypeInfo) {
        this.salesTypeInfo = salesTypeInfo;
    }

    /**
     * 出票城市
     */
    public int getSendTicketCity() {
        return this.sendTicketCity;
    }

    public void setSendTicketCity(int sendTicketCity) {
        this.sendTicketCity = sendTicketCity;
    }

    /**
     * 是否延长支付
     */
    public boolean getNeedPayDelay() {
        return this.needPayDelay;
    }

    public void setNeedPayDelay(boolean needPayDelay) {
        this.needPayDelay = needPayDelay;
    }

    /**
     * 是否手工单
     */
    public boolean getIsManual() {
        return this.isManual;
    }

    public void setIsManual(boolean isManual) {
        this.isManual = isManual;
    }

    /**
     * 是否需要出票（True或False）
     */
    public boolean getNeedPrintTicket() {
        return this.needPrintTicket;
    }

    public void setNeedPrintTicket(boolean needPrintTicket) {
        this.needPrintTicket = needPrintTicket;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final OfflineMiscInfoType other = (OfflineMiscInfoType)obj;
        return
            Objects.equal(this.contactRemark, other.contactRemark) && 
            Objects.equal(this.operatorInfo, other.operatorInfo) && 
            Objects.equal(this.postponeFee, other.postponeFee) && 
            Objects.equal(this.descInfo, other.descInfo) && 
            Objects.equal(this.salesTypeInfo, other.salesTypeInfo) && 
            Objects.equal(this.sendTicketCity, other.sendTicketCity) && 
            Objects.equal(this.needPayDelay, other.needPayDelay) && 
            Objects.equal(this.isManual, other.isManual) && 
            Objects.equal(this.needPrintTicket, other.needPrintTicket);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.contactRemark);
        result = 31 * result + Objects.hashCode(this.operatorInfo);
        result = 31 * result + Objects.hashCode(this.postponeFee);
        result = 31 * result + Objects.hashCode(this.descInfo);
        result = 31 * result + Objects.hashCode(this.salesTypeInfo);
        result = 31 * result + Objects.hashCode(this.sendTicketCity);
        result = 31 * result + Objects.hashCode(this.needPayDelay);
        result = 31 * result + Objects.hashCode(this.isManual);
        result = 31 * result + Objects.hashCode(this.needPrintTicket);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("contactRemark", contactRemark)
            .add("operatorInfo", operatorInfo)
            .add("postponeFee", postponeFee)
            .add("descInfo", descInfo)
            .add("salesTypeInfo", salesTypeInfo)
            .add("sendTicketCity", sendTicketCity)
            .add("needPayDelay", needPayDelay)
            .add("isManual", isManual)
            .add("needPrintTicket", needPrintTicket)
            .toString();
    }

}