/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.intlflight.ordering.contract.saveorder.v2;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 *         操作人信息类型
 *       
 */
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OperatorInfoType", namespace = "urn:com:ctrip:flight:intl:booking:order:contract:saveorder:v2", propOrder = {
    "eid",
    "processOper",
    "ucid"
})
@SuppressWarnings("all")
public class OperatorInfoType implements Serializable {

    private static final long serialVersionUID = 1L;

    public OperatorInfoType(
        String eid, 
        String processOper, 
        String ucid) {
        this.eid = eid;
        this.processOper = processOper;
        this.ucid = ucid;
    }

    public OperatorInfoType() {
    }

    @JsonProperty("EID")
    @XmlElement(name = "EID")
    private String eid;

    @JsonProperty("ProcessOper")
    @XmlElement(name = "ProcessOper")
    private String processOper;

    @JsonProperty("Ucid")
    @XmlElement(name = "Ucid")
    private String ucid;

    /**
     * 订单操作员Id
     */
    public String getEid() {
        return this.eid;
    }

    public void setEid(String eid) {
        this.eid = eid;
    }

    /**
     * 当初操作员Id
     */
    public String getProcessOper() {
        return this.processOper;
    }

    public void setProcessOper(String processOper) {
        this.processOper = processOper;
    }

    /**
     * callid
     */
    public String getUcid() {
        return this.ucid;
    }

    public void setUcid(String ucid) {
        this.ucid = ucid;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final OperatorInfoType other = (OperatorInfoType)obj;
        return
            Objects.equal(this.eid, other.eid) && 
            Objects.equal(this.processOper, other.processOper) && 
            Objects.equal(this.ucid, other.ucid);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.eid);
        result = 31 * result + Objects.hashCode(this.processOper);
        result = 31 * result + Objects.hashCode(this.ucid);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("eid", eid)
            .add("processOper", processOper)
            .add("ucid", ucid)
            .toString();
    }

}