/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
@XmlSchema(namespace = "urn:com:ctrip:flight:intl:booking:order:contract:saveorder:v2", elementFormDefault = XmlNsForm.QUALIFIED)
package contract.saveorder.v2;

import javax.xml.bind.annotation.XmlNsForm;
import javax.xml.bind.annotation.XmlSchema;
