/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.intlflight.ordering.contract.saveorder.v2;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Calendar;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 套餐产品
 */
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PackageAttachInfoType", namespace = "urn:com:ctrip:flight:intl:booking:order:contract:saveorder:v2", propOrder = {
    "packageType",
    "attachProduct",
    "attachName",
    "points",
    "attachDesc",
    "expireTime"
})
@SuppressWarnings("all")
public class PackageAttachInfoType implements Serializable {

    private static final long serialVersionUID = 1L;

    public PackageAttachInfoType(
        int packageType, 
        int attachProduct, 
        String attachName, 
        BigDecimal points, 
        String attachDesc, 
        Calendar expireTime) {
        this.packageType = packageType;
        this.attachProduct = attachProduct;
        this.attachName = attachName;
        this.points = points;
        this.attachDesc = attachDesc;
        this.expireTime = expireTime;
    }

    public PackageAttachInfoType() {
        this.points = new BigDecimal(0);
        this.expireTime = new java.util.GregorianCalendar(1, Calendar.JANUARY, 1, 0, 0, 0);
        this.expireTime.setTimeZone(sun.util.calendar.ZoneInfo.getTimeZone("UTC"));
    }

    @JsonProperty("PackageType")
    @XmlElement(name = "PackageType")
    private int packageType;

    @JsonProperty("AttachProduct")
    @XmlElement(name = "AttachProduct")
    private int attachProduct;

    @JsonProperty("AttachName")
    @XmlElement(name = "AttachName")
    private String attachName;

    @JsonProperty("Points")
    @XmlElement(name = "Points")
    private BigDecimal points;

    @JsonProperty("AttachDesc")
    @XmlElement(name = "AttachDesc")
    private String attachDesc;

    @JsonProperty("ExpireTime")
    @XmlElement(name = "ExpireTime")
    private Calendar expireTime;

    /**
     * 套餐礼品类型：
     *             4.网络专享//暂时不用
     *             5.网络专享（积分优惠券）
     *             8.礼品卡
     *             14.租车优惠券
     *             15.景酒优惠券
     *             16.酒店优惠券
     *             17.接送机券
     *             18.玩乐券
     *             19.签证券
     *             其中4、5、14~19为三选一产品
     *             8为X产品
     */
    public int getPackageType() {
        return this.packageType;
    }

    public void setPackageType(int packageType) {
        this.packageType = packageType;
    }

    /**
     * 打包附加产品类别(6:积分优惠券)
     */
    public int getAttachProduct() {
        return this.attachProduct;
    }

    public void setAttachProduct(int attachProduct) {
        this.attachProduct = attachProduct;
    }

    /**
     * 套餐类型(一般性政策NA = 0, 商务优选 BusinessPriority = 1, 旅行套餐 TravelPackage = 2, 优选套餐 PriorityPackage = 3, 航司直营 AirLineMarketing = 4)
     */
    public String getAttachName() {
        return this.attachName;
    }

    public void setAttachName(String attachName) {
        this.attachName = attachName;
    }

    /**
     * 套餐积分
     */
    public BigDecimal getPoints() {
        return this.points;
    }

    public void setPoints(BigDecimal points) {
        this.points = points;
    }

    /**
     * 产品描述
     */
    public String getAttachDesc() {
        return this.attachDesc;
    }

    public void setAttachDesc(String attachDesc) {
        this.attachDesc = attachDesc;
    }

    /**
     * 有效期
     */
    public Calendar getExpireTime() {
        return this.expireTime;
    }

    public void setExpireTime(Calendar expireTime) {
        this.expireTime = expireTime;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final PackageAttachInfoType other = (PackageAttachInfoType)obj;
        return
            Objects.equal(this.packageType, other.packageType) && 
            Objects.equal(this.attachProduct, other.attachProduct) && 
            Objects.equal(this.attachName, other.attachName) && 
            Objects.equal(this.points, other.points) && 
            Objects.equal(this.attachDesc, other.attachDesc) && 
            Objects.equal(this.expireTime, other.expireTime);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.packageType);
        result = 31 * result + Objects.hashCode(this.attachProduct);
        result = 31 * result + Objects.hashCode(this.attachName);
        result = 31 * result + Objects.hashCode(this.points);
        result = 31 * result + Objects.hashCode(this.attachDesc);
        result = 31 * result + Objects.hashCode(this.expireTime);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("packageType", packageType)
            .add("attachProduct", attachProduct)
            .add("attachName", attachName)
            .add("points", points)
            .add("attachDesc", attachDesc)
            .add("expireTime", expireTime)
            .toString();
    }

}