/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.intlflight.ordering.contract.saveorder.v2;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlType;

/**
 * 支付信息
 */
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PaymentInfoType", namespace = "urn:com:ctrip:flight:intl:booking:order:contract:saveorder:v2", propOrder = {
    "payInfoList",
    "externalNO",
    "cCardPayFee"
})
@SuppressWarnings("all")
public class PaymentInfoType implements Serializable {

    private static final long serialVersionUID = 1L;

    public PaymentInfoType(
        List<PayInfoType> payInfoList,
        String externalNO, 
        BigDecimal cCardPayFee) {
        this.payInfoList = payInfoList;
        this.externalNO = externalNO;
        this.cCardPayFee = cCardPayFee;
    }

    public PaymentInfoType() {
        this.cCardPayFee = new BigDecimal(0);
    }

    @JsonProperty("PayInfoList")
    @XmlElement(name = "PayInfo")
    @XmlElementWrapper(name = "PayInfoList")
    private List<PayInfoType> payInfoList;

    @JsonProperty("ExternalNO")
    @XmlElement(name = "ExternalNO")
    private String externalNO;

    @JsonProperty("CCardPayFee")
    @XmlElement(name = "CCardPayFee")
    private BigDecimal cCardPayFee;

    /**
     * *支付类型，需要适配成机票自身支付类型
     */
    public List<PayInfoType> getPayInfoList() {
        return this.payInfoList;
    }

    public void setPayInfoList(List<PayInfoType> payInfoList) {
        this.payInfoList = payInfoList;
    }

    /**
     * *订单支付流水号
     */
    public String getExternalNO() {
        return this.externalNO;
    }

    public void setExternalNO(String externalNO) {
        this.externalNO = externalNO;
    }

    /**
     * 外卡服务费
     */
    public BigDecimal getCCardPayFee() {
        return this.cCardPayFee;
    }

    public void setCCardPayFee(BigDecimal cCardPayFee) {
        this.cCardPayFee = cCardPayFee;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final PaymentInfoType other = (PaymentInfoType)obj;
        return
            Objects.equal(this.payInfoList, other.payInfoList) && 
            Objects.equal(this.externalNO, other.externalNO) && 
            Objects.equal(this.cCardPayFee, other.cCardPayFee);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.payInfoList);
        result = 31 * result + Objects.hashCode(this.externalNO);
        result = 31 * result + Objects.hashCode(this.cCardPayFee);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("payInfoList", payInfoList)
            .add("externalNO", externalNO)
            .add("cCardPayFee", cCardPayFee)
            .toString();
    }

}