// Generated by eBay Common SDK Platform
package contract.saveorder.v2;

import com.fasterxml.jackson.annotation.JsonValue;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlEnumValue;

/**
 * 使用优惠类型
 */
@XmlType(name = "PromotionTypeEnum")
@XmlEnum
@SuppressWarnings("all")
public enum PromotionTypeEnum {

    /**
     * 使用权益
     */
    @XmlEnumValue("UseInterests")
    UseInterests(0, "UseInterests");

    private final int intValue;
    private final String value;

    PromotionTypeEnum(int intValue, String value) {
        this.intValue = intValue;
        this.value = value;
    }

    public int getValue() {
        return intValue;
    }

    @JsonValue
    public String value() {
        return value;
    }

    public static PromotionTypeEnum fromValue(String v) {
        for (PromotionTypeEnum e: PromotionTypeEnum.values()) {
            if (e.value.equalsIgnoreCase(v)) {
                return e;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public static PromotionTypeEnum findByValue(int value) {
        switch (value) {
            case 0:
                return UseInterests;
            default:
                return null;
        }
    }
}