/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package contract.saveorder.v2;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.io.Serializable;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlType;

/**
 * 订位相关信息
 */
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReservationInfoType", namespace = "urn:com:ctrip:flight:intl:booking:order:contract:saveorder:v2", propOrder = {
    "reservationMode",
    "pnrRecordList"
})
@SuppressWarnings("all")
public class ReservationInfoType implements Serializable {

    private static final long serialVersionUID = 1L;

    public ReservationInfoType(
        String reservationMode, 
        List<PNRRecordInfoType> pnrRecordList) {
        this.reservationMode = reservationMode;
        this.pnrRecordList = pnrRecordList;
    }

    public ReservationInfoType() {
    }

    @JsonProperty("ReservationMode")
    @XmlElement(name = "ReservationMode")
    private String reservationMode;

    @JsonProperty("PNRRecordList")
    @XmlElement(name = "PNRRecordInfo")
    @XmlElementWrapper(name = "PNRRecordList")
    private List<PNRRecordInfoType> pnrRecordList;

    /**
     * 订位模式A自动订位/M人工订位/默认A
     */
    public String getReservationMode() {
        return this.reservationMode;
    }

    public void setReservationMode(String reservationMode) {
        this.reservationMode = reservationMode;
    }

    /**
     * 订位记录列表信息
     */
    public List<PNRRecordInfoType> getPnrRecordList() {
        return this.pnrRecordList;
    }

    public void setPnrRecordList(List<PNRRecordInfoType> pnrRecordList) {
        this.pnrRecordList = pnrRecordList;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final ReservationInfoType other = (ReservationInfoType)obj;
        return
            Objects.equal(this.reservationMode, other.reservationMode) && 
            Objects.equal(this.pnrRecordList, other.pnrRecordList);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.reservationMode);
        result = 31 * result + Objects.hashCode(this.pnrRecordList);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("reservationMode", reservationMode)
            .add("pnrRecordList", pnrRecordList)
            .toString();
    }

}