// Generated by eBay Common SDK Platform
package com.ctrip.intlflight.ordering.contract.saveorder.v2;

import com.fasterxml.jackson.annotation.JsonValue;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlEnumValue;

/**
 * 页面流程
 */
@XmlType(name = "SalesTypeType")
@XmlEnum
@SuppressWarnings("all")
public enum SalesTypeType {

    /**
     * 未指定
     */
    @XmlEnumValue("None")
    None(0, "None"),

    /**
     * 英文
     */
    @XmlEnumValue("English")
    English(1, "English"),

    /**
     * 度假
     */
    @XmlEnumValue("Holiday")
    Holiday(2, "Holiday"),

    /**
     * 机酒
     */
    @XmlEnumValue("AirHotelIntl")
    AirHotelIntl(3, "AirHotelIntl");

    private final int intValue;
    private final String value;

    SalesTypeType(int intValue, String value) {
        this.intValue = intValue;
        this.value = value;
    }

    public int getValue() {
        return intValue;
    }

    @JsonValue
    public String value() {
        return value;
    }

    public static SalesTypeType fromValue(String v) {
        for (SalesTypeType e: SalesTypeType.values()) {
            if (e.value.equalsIgnoreCase(v)) {
                return e;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public static SalesTypeType findByValue(int value) {
        switch (value) {
            case 0:
                return None;
            case 1:
                return English;
            case 2:
                return Holiday;
            case 3:
                return AirHotelIntl;
            default:
                return null;
        }
    }
}