/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.intlflight.ordering.contract.saveorder.v2;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.io.Serializable;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlType;

/**
 * 银行卡优惠信息保存实体
 */
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SavePaymentType", namespace = "urn:com:ctrip:flight:intl:booking:order:contract:saveorder:v2", propOrder = {
    "payLimit",
    "paymentInfo"
})
@SuppressWarnings("all")
public class SavePaymentType implements Serializable {

    private static final long serialVersionUID = 1L;

    public SavePaymentType(
        String payLimit, 
        List<SavePayDetailType> paymentInfo) {
        this.payLimit = payLimit;
        this.paymentInfo = paymentInfo;
    }

    public SavePaymentType() {
    }

    @JsonProperty("PayLimit")
    @XmlElement(name = "PayLimit")
    private String payLimit;

    @JsonProperty("PaymentInfo")
    @XmlElement(name = "PaymentDetailInfo")
    @XmlElementWrapper(name = "PaymentInfo")
    private List<SavePayDetailType> paymentInfo;

    /**
     * 白名单：支持的支付方式
     */
    public String getPayLimit() {
        return this.payLimit;
    }

    public void setPayLimit(String payLimit) {
        this.payLimit = payLimit;
    }

    /**
     * 优惠卡段信息
     */
    public List<SavePayDetailType> getPaymentInfo() {
        return this.paymentInfo;
    }

    public void setPaymentInfo(List<SavePayDetailType> paymentInfo) {
        this.paymentInfo = paymentInfo;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final SavePaymentType other = (SavePaymentType)obj;
        return
            Objects.equal(this.payLimit, other.payLimit) && 
            Objects.equal(this.paymentInfo, other.paymentInfo);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.payLimit);
        result = 31 * result + Objects.hashCode(this.paymentInfo);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("payLimit", payLimit)
            .add("paymentInfo", paymentInfo)
            .toString();
    }

}