/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.intlflight.ordering.contract.saveorder.v2;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 优惠卡段信息
 */
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SavePayDetailType", namespace = "urn:com:ctrip:flight:intl:booking:order:contract:saveorder:v2", propOrder = {
    "payType",
    "payTypeName",
    "maxActivityCount",
    "payWay",
    "startNo",
    "endNo"
})
@SuppressWarnings("all")
public class SavePayDetailType implements Serializable {

    private static final long serialVersionUID = 1L;

    public SavePayDetailType(
        int payType, 
        String payTypeName, 
        int maxActivityCount, 
        String payWay, 
        String startNo, 
        String endNo) {
        this.payType = payType;
        this.payTypeName = payTypeName;
        this.maxActivityCount = maxActivityCount;
        this.payWay = payWay;
        this.startNo = startNo;
        this.endNo = endNo;
    }

    public SavePayDetailType() {
    }

    @JsonProperty("PayType")
    @XmlElement(name = "PayType")
    private int payType;

    @JsonProperty("PayTypeName")
    @XmlElement(name = "PayTypeName")
    private String payTypeName;

    @JsonProperty("MaxActivityCount")
    @XmlElement(name = "MaxActivityCount")
    private int maxActivityCount;

    @JsonProperty("PayWay")
    @XmlElement(name = "PayWay")
    private String payWay;

    @JsonProperty("StartNo")
    @XmlElement(name = "StartNo")
    private String startNo;

    @JsonProperty("EndNo")
    @XmlElement(name = "EndNo")
    private String endNo;

    /**
     * 支付方式
     */
    public int getPayType() {
        return this.payType;
    }

    public void setPayType(int payType) {
        this.payType = payType;
    }

    /**
     * 支付方式
     */
    public String getPayTypeName() {
        return this.payTypeName;
    }

    public void setPayTypeName(String payTypeName) {
        this.payTypeName = payTypeName;
    }

    /**
     * 最大限制次数
     */
    public int getMaxActivityCount() {
        return this.maxActivityCount;
    }

    public void setMaxActivityCount(int maxActivityCount) {
        this.maxActivityCount = maxActivityCount;
    }

    /**
     * PaymentWay
     */
    public String getPayWay() {
        return this.payWay;
    }

    public void setPayWay(String payWay) {
        this.payWay = payWay;
    }

    /**
     * 卡段起始
     */
    public String getStartNo() {
        return this.startNo;
    }

    public void setStartNo(String startNo) {
        this.startNo = startNo;
    }

    /**
     * 卡段结束
     */
    public String getEndNo() {
        return this.endNo;
    }

    public void setEndNo(String endNo) {
        this.endNo = endNo;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final SavePayDetailType other = (SavePayDetailType)obj;
        return
            Objects.equal(this.payType, other.payType) && 
            Objects.equal(this.payTypeName, other.payTypeName) && 
            Objects.equal(this.maxActivityCount, other.maxActivityCount) && 
            Objects.equal(this.payWay, other.payWay) && 
            Objects.equal(this.startNo, other.startNo) && 
            Objects.equal(this.endNo, other.endNo);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.payType);
        result = 31 * result + Objects.hashCode(this.payTypeName);
        result = 31 * result + Objects.hashCode(this.maxActivityCount);
        result = 31 * result + Objects.hashCode(this.payWay);
        result = 31 * result + Objects.hashCode(this.startNo);
        result = 31 * result + Objects.hashCode(this.endNo);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("payType", payType)
            .add("payTypeName", payTypeName)
            .add("maxActivityCount", maxActivityCount)
            .add("payWay", payWay)
            .add("startNo", startNo)
            .add("endNo", endNo)
            .toString();
    }

}