/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.intlflight.ordering.contract.saveorder.v2;

import com.ctrip.intlflight.ordering.contract.commontype.v1.ErrorResultType;
import com.ctrip.intlflight.ordering.contract.commontype.v1.ResponseHeaderType;
import com.ctriposs.baiji.rpc.common.HasResponseStatus;
import com.ctriposs.baiji.rpc.common.types.ResponseStatusType;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.io.Serializable;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 如果处理结果是错误，ErrorResult会被填充；否则OrderID会被填充
 */
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "SaveOrderResponse", namespace = "urn:com:ctrip:flight:intl:booking:order:contract:saveorder:v2")
@XmlType(name = "SaveOrderResponseType", namespace = "urn:com:ctrip:flight:intl:booking:order:contract:saveorder:v2", propOrder = {
    "responseHeader",
    "responseStatus",
    "orderID",
    "externalNO",
    "errorResult",
    "autoReservSnNoList",
    "xProductFailList",
    "amountDetail",
    "payExpiryTime",
    "insuranceAccountSplit",
    "paymentDeadline",
    "version"
})
@SuppressWarnings("all")
public class SaveOrderResponseType implements HasResponseStatus, Serializable {

    private static final long serialVersionUID = 1L;

    public SaveOrderResponseType(
        ResponseHeaderType responseHeader,
        ResponseStatusType responseStatus, 
        long orderID, 
        String externalNO, 
        ErrorResultType errorResult,
        List<String> autoReservSnNoList, 
        List<XProductFailInfoType> xProductFailList,
        String amountDetail, 
        int payExpiryTime, 
        String insuranceAccountSplit, 
        String paymentDeadline, 
        int version) {
        this.responseHeader = responseHeader;
        this.responseStatus = responseStatus;
        this.orderID = orderID;
        this.externalNO = externalNO;
        this.errorResult = errorResult;
        this.autoReservSnNoList = autoReservSnNoList;
        this.xProductFailList = xProductFailList;
        this.amountDetail = amountDetail;
        this.payExpiryTime = payExpiryTime;
        this.insuranceAccountSplit = insuranceAccountSplit;
        this.paymentDeadline = paymentDeadline;
        this.version = version;
    }

    public SaveOrderResponseType() {
    }

    @JsonProperty("ResponseHeader")
    @XmlElement(name = "ResponseHeader")
    private ResponseHeaderType responseHeader;

    @JsonProperty("ResponseStatus")
    @XmlElement(name = "ResponseStatus")
    private ResponseStatusType responseStatus;

    @JsonProperty("OrderID")
    @XmlElement(name = "OrderID")
    private long orderID;

    @JsonProperty("ExternalNO")
    @XmlElement(name = "ExternalNO")
    private String externalNO;

    @JsonProperty("ErrorResult")
    @XmlElement(name = "ErrorResult")
    private ErrorResultType errorResult;

    @JsonProperty("AutoReservSnNoList")
    @XmlElement(name = "AutoReservSnNo")
    @XmlElementWrapper(name = "AutoReservSnNoList")
    private List<String> autoReservSnNoList;

    @JsonProperty("XProductFailList")
    @XmlElement(name = "XProductFailInfo")
    @XmlElementWrapper(name = "XProductFailList")
    private List<XProductFailInfoType> xProductFailList;

    @JsonProperty("AmountDetail")
    @XmlElement(name = "AmountDetail")
    private String amountDetail;

    @JsonProperty("PayExpiryTime")
    @XmlElement(name = "PayExpiryTime")
    private int payExpiryTime;

    @JsonProperty("InsuranceAccountSplit")
    @XmlElement(name = "InsuranceAccountSplit")
    private String insuranceAccountSplit;

    @JsonProperty("PaymentDeadline")
    @XmlElement(name = "PaymentDeadline")
    private String paymentDeadline;

    @JsonProperty("Version")
    @XmlElement(name = "Version")
    private int version;

    public ResponseHeaderType getResponseHeader() {
        return this.responseHeader;
    }

    public void setResponseHeader(ResponseHeaderType responseHeader) {
        this.responseHeader = responseHeader;
    }

    public ResponseStatusType getResponseStatus() {
        return this.responseStatus;
    }

    public void setResponseStatus(ResponseStatusType responseStatus) {
        this.responseStatus = responseStatus;
    }

    /**
     * 订单编号
     */
    public long getOrderID() {
        return this.orderID;
    }

    public void setOrderID(long orderID) {
        this.orderID = orderID;
    }

    public String getExternalNO() {
        return this.externalNO;
    }

    public void setExternalNO(String externalNO) {
        this.externalNO = externalNO;
    }

    public ErrorResultType getErrorResult() {
        return this.errorResult;
    }

    public void setErrorResult(ErrorResultType errorResult) {
        this.errorResult = errorResult;
    }

    /**
     * 订位TokenNumber，多PU会存在多个
     */
    public List<String> getAutoReservSnNoList() {
        return this.autoReservSnNoList;
    }

    public void setAutoReservSnNoList(List<String> autoReservSnNoList) {
        this.autoReservSnNoList = autoReservSnNoList;
    }

    /**
     * X产品订购失败列表
     */
    public List<XProductFailInfoType> getXProductFailList() {
        return this.xProductFailList;
    }

    public void setXProductFailList(List<XProductFailInfoType> xProductFailList) {
        this.xProductFailList = xProductFailList;
    }

    /**
     * 1：机票+税
     *             2：X产品
     *             3：配送费
     *             4：优惠券金额
     */
    public String getAmountDetail() {
        return this.amountDetail;
    }

    public void setAmountDetail(String amountDetail) {
        this.amountDetail = amountDetail;
    }

    /**
     * 支付时限(分钟)
     */
    public int getPayExpiryTime() {
        return this.payExpiryTime;
    }

    public void setPayExpiryTime(int payExpiryTime) {
        this.payExpiryTime = payExpiryTime;
    }

    /**
     * 保险分账信息
     *             [{Provider:1,Amount:20,Currency:"CNY"},{Provider:2,Amount:20,Currency:"CNY"}]
     *             Provider:账户类型:1.携程保代，2.众诚泰
     *             Amount:当前账户类型的保险总金额
     *             Currency:保险币种
     */
    public String getInsuranceAccountSplit() {
        return this.insuranceAccountSplit;
    }

    public void setInsuranceAccountSplit(String insuranceAccountSplit) {
        this.insuranceAccountSplit = insuranceAccountSplit;
    }

    /**
     * 支付截止时间（北京） yyyy-MM-dd HH:mm:ss
     */
    public String getPaymentDeadline() {
        return this.paymentDeadline;
    }

    public void setPaymentDeadline(String paymentDeadline) {
        this.paymentDeadline = paymentDeadline;
    }

    /**
     * 版本号：0表示LTP支付模式；1表示bill单模式
     */
    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final SaveOrderResponseType other = (SaveOrderResponseType)obj;
        return
            Objects.equal(this.responseHeader, other.responseHeader) && 
            Objects.equal(this.responseStatus, other.responseStatus) && 
            Objects.equal(this.orderID, other.orderID) && 
            Objects.equal(this.externalNO, other.externalNO) && 
            Objects.equal(this.errorResult, other.errorResult) && 
            Objects.equal(this.autoReservSnNoList, other.autoReservSnNoList) && 
            Objects.equal(this.xProductFailList, other.xProductFailList) && 
            Objects.equal(this.amountDetail, other.amountDetail) && 
            Objects.equal(this.payExpiryTime, other.payExpiryTime) && 
            Objects.equal(this.insuranceAccountSplit, other.insuranceAccountSplit) && 
            Objects.equal(this.paymentDeadline, other.paymentDeadline) && 
            Objects.equal(this.version, other.version);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.responseHeader);
        result = 31 * result + Objects.hashCode(this.responseStatus);
        result = 31 * result + Objects.hashCode(this.orderID);
        result = 31 * result + Objects.hashCode(this.externalNO);
        result = 31 * result + Objects.hashCode(this.errorResult);
        result = 31 * result + Objects.hashCode(this.autoReservSnNoList);
        result = 31 * result + Objects.hashCode(this.xProductFailList);
        result = 31 * result + Objects.hashCode(this.amountDetail);
        result = 31 * result + Objects.hashCode(this.payExpiryTime);
        result = 31 * result + Objects.hashCode(this.insuranceAccountSplit);
        result = 31 * result + Objects.hashCode(this.paymentDeadline);
        result = 31 * result + Objects.hashCode(this.version);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("responseHeader", responseHeader)
            .add("responseStatus", responseStatus)
            .add("orderID", orderID)
            .add("externalNO", externalNO)
            .add("errorResult", errorResult)
            .add("autoReservSnNoList", autoReservSnNoList)
            .add("xProductFailList", xProductFailList)
            .add("amountDetail", amountDetail)
            .add("payExpiryTime", payExpiryTime)
            .add("insuranceAccountSplit", insuranceAccountSplit)
            .add("paymentDeadline", paymentDeadline)
            .add("version", version)
            .toString();
    }

}