/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.intlflight.ordering.contract.saveorder.v2;

import com.ctrip.intlflight.ordering.contract.commontype.v1.RequestHeaderType;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.io.Serializable;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 *         订单保存请求实体
 *         原有下单接口会用请求中的退改签信息ID去查询相关信息写入数据库，现有接口直接使用FlightProductRequest中的退改签信息
 *       
 */
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "SaveOrderRequest", namespace = "urn:com:ctrip:flight:intl:booking:order:contract:saveorder:v2")
@XmlType(name = "SaveOrderRequestType", namespace = "urn:com:ctrip:flight:intl:booking:order:contract:saveorder:v2", propOrder = {
    "requestHeader",
    "action",
    "orderID",
    "searchCriteriaToken",
    "routeSearchToken",
    "qteInfo",
    "travelerInfoList",
    "contactInfo",
    "deliveryInfo",
    "paymentInfo",
    "orderMiscInfo",
    "xProductList",
    "useCouponInfoList",
    "usePromotionInfoList",
    "packageAttachInfoList"
})
@SuppressWarnings("all")
public class SaveOrderRequestType implements Serializable {

    private static final long serialVersionUID = 1L;

    public SaveOrderRequestType(
        RequestHeaderType requestHeader,
        ActionType action,
        long orderID, 
        String searchCriteriaToken, 
        String routeSearchToken, 
        QTEInfoType qteInfo,
        List<TravelerInfoType> travelerInfoList,
        ContactInfoType contactInfo,
        DeliveryInfoType deliveryInfo,
        PaymentInfoType paymentInfo,
        OrderMiscInfoType orderMiscInfo,
        List<XProductInfoType> xProductList,
        List<UseCouponInfoType> useCouponInfoList,
        List<UsePromotionInfoType> usePromotionInfoList,
        List<PackageAttachInfoType> packageAttachInfoList) {
        this.requestHeader = requestHeader;
        this.action = action;
        this.orderID = orderID;
        this.searchCriteriaToken = searchCriteriaToken;
        this.routeSearchToken = routeSearchToken;
        this.qteInfo = qteInfo;
        this.travelerInfoList = travelerInfoList;
        this.contactInfo = contactInfo;
        this.deliveryInfo = deliveryInfo;
        this.paymentInfo = paymentInfo;
        this.orderMiscInfo = orderMiscInfo;
        this.xProductList = xProductList;
        this.useCouponInfoList = useCouponInfoList;
        this.usePromotionInfoList = usePromotionInfoList;
        this.packageAttachInfoList = packageAttachInfoList;
    }

    public SaveOrderRequestType() {
    }

    @JsonProperty("RequestHeader")
    @XmlElement(name = "RequestHeader")
    private RequestHeaderType requestHeader;

    @JsonProperty("Action")
    @XmlElement(name = "Action", nillable = true)
    private ActionType action;

    @JsonProperty("OrderID")
    @XmlElement(name = "OrderID")
    private long orderID;

    @JsonProperty("SearchCriteriaToken")
    @XmlElement(name = "SearchCriteriaToken")
    private String searchCriteriaToken;

    @JsonProperty("RouteSearchToken")
    @XmlElement(name = "RouteSearchToken")
    private String routeSearchToken;

    @JsonProperty("QTEInfo")
    @XmlElement(name = "QTEInfo")
    private QTEInfoType qteInfo;

    @JsonProperty("TravelerInfoList")
    @XmlElement(name = "TravelerInfo")
    @XmlElementWrapper(name = "TravelerInfoList")
    private List<TravelerInfoType> travelerInfoList;

    @JsonProperty("ContactInfo")
    @XmlElement(name = "ContactInfo")
    private ContactInfoType contactInfo;

    @JsonProperty("DeliveryInfo")
    @XmlElement(name = "DeliveryInfo")
    private DeliveryInfoType deliveryInfo;

    @JsonProperty("PaymentInfo")
    @XmlElement(name = "PaymentInfo")
    private PaymentInfoType paymentInfo;

    @JsonProperty("OrderMiscInfo")
    @XmlElement(name = "OrderMiscInfo")
    private OrderMiscInfoType orderMiscInfo;

    @JsonProperty("XProductList")
    @XmlElement(name = "XProductInfo")
    @XmlElementWrapper(name = "XProductList")
    private List<XProductInfoType> xProductList;

    @JsonProperty("UseCouponInfoList")
    @XmlElement(name = "UseCouponInfo")
    @XmlElementWrapper(name = "UseCouponInfoList")
    private List<UseCouponInfoType> useCouponInfoList;

    @JsonProperty("UsePromotionInfoList")
    @XmlElement(name = "UsePromotionInfo")
    @XmlElementWrapper(name = "UsePromotionInfoList")
    private List<UsePromotionInfoType> usePromotionInfoList;

    @JsonProperty("PackageAttachInfoList")
    @XmlElement(name = "PackageAttachInfo")
    @XmlElementWrapper(name = "PackageAttachInfoList")
    private List<PackageAttachInfoType> packageAttachInfoList;

    public RequestHeaderType getRequestHeader() {
        return this.requestHeader;
    }

    public void setRequestHeader(RequestHeaderType requestHeader) {
        this.requestHeader = requestHeader;
    }

    /**
     * *请求模式，常用的是三种模式：CreateOrder,ModifyOrder,SubmitOrder
     */
    public ActionType getAction() {
        return this.action;
    }

    public void setAction(ActionType action) {
        this.action = action;
    }

    /**
     * 订单编号
     */
    public long getOrderID() {
        return this.orderID;
    }

    public void setOrderID(long orderID) {
        this.orderID = orderID;
    }

    /**
     * *查询条件Token
     */
    public String getSearchCriteriaToken() {
        return this.searchCriteriaToken;
    }

    public void setSearchCriteriaToken(String searchCriteriaToken) {
        this.searchCriteriaToken = searchCriteriaToken;
    }

    /**
     * *路由查询Token
     */
    public String getRouteSearchToken() {
        return this.routeSearchToken;
    }

    public void setRouteSearchToken(String routeSearchToken) {
        this.routeSearchToken = routeSearchToken;
    }

    /**
     * *价格信息（必传）
     */
    public QTEInfoType getQteInfo() {
        return this.qteInfo;
    }

    public void setQteInfo(QTEInfoType qteInfo) {
        this.qteInfo = qteInfo;
    }

    /**
     * *乘机人信息（必传）
     */
    public List<TravelerInfoType> getTravelerInfoList() {
        return this.travelerInfoList;
    }

    public void setTravelerInfoList(List<TravelerInfoType> travelerInfoList) {
        this.travelerInfoList = travelerInfoList;
    }

    /**
     * *联系人信息
     */
    public ContactInfoType getContactInfo() {
        return this.contactInfo;
    }

    public void setContactInfo(ContactInfoType contactInfo) {
        this.contactInfo = contactInfo;
    }

    /**
     * *配送信息
     */
    public DeliveryInfoType getDeliveryInfo() {
        return this.deliveryInfo;
    }

    public void setDeliveryInfo(DeliveryInfoType deliveryInfo) {
        this.deliveryInfo = deliveryInfo;
    }

    /**
     * *支付信息（提交订单时传值）
     */
    public PaymentInfoType getPaymentInfo() {
        return this.paymentInfo;
    }

    public void setPaymentInfo(PaymentInfoType paymentInfo) {
        this.paymentInfo = paymentInfo;
    }

    /**
     * *下单综合信息（如外部订单号等）
     */
    public OrderMiscInfoType getOrderMiscInfo() {
        return this.orderMiscInfo;
    }

    public void setOrderMiscInfo(OrderMiscInfoType orderMiscInfo) {
        this.orderMiscInfo = orderMiscInfo;
    }

    /**
     * X 产品信息集合
     */
    public List<XProductInfoType> getXProductList() {
        return this.xProductList;
    }

    public void setXProductList(List<XProductInfoType> xProductList) {
        this.xProductList = xProductList;
    }

    /**
     * 使用优惠劵信息
     */
    public List<UseCouponInfoType> getUseCouponInfoList() {
        return this.useCouponInfoList;
    }

    public void setUseCouponInfoList(List<UseCouponInfoType> useCouponInfoList) {
        this.useCouponInfoList = useCouponInfoList;
    }

    /**
     * 使用优惠信息(权益等)
     */
    public List<UsePromotionInfoType> getUsePromotionInfoList() {
        return this.usePromotionInfoList;
    }

    public void setUsePromotionInfoList(List<UsePromotionInfoType> usePromotionInfoList) {
        this.usePromotionInfoList = usePromotionInfoList;
    }

    /**
     * 积分套餐
     */
    public List<PackageAttachInfoType> getPackageAttachInfoList() {
        return this.packageAttachInfoList;
    }

    public void setPackageAttachInfoList(List<PackageAttachInfoType> packageAttachInfoList) {
        this.packageAttachInfoList = packageAttachInfoList;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final SaveOrderRequestType other = (SaveOrderRequestType)obj;
        return
            Objects.equal(this.requestHeader, other.requestHeader) && 
            Objects.equal(this.action, other.action) && 
            Objects.equal(this.orderID, other.orderID) && 
            Objects.equal(this.searchCriteriaToken, other.searchCriteriaToken) && 
            Objects.equal(this.routeSearchToken, other.routeSearchToken) && 
            Objects.equal(this.qteInfo, other.qteInfo) && 
            Objects.equal(this.travelerInfoList, other.travelerInfoList) && 
            Objects.equal(this.contactInfo, other.contactInfo) && 
            Objects.equal(this.deliveryInfo, other.deliveryInfo) && 
            Objects.equal(this.paymentInfo, other.paymentInfo) && 
            Objects.equal(this.orderMiscInfo, other.orderMiscInfo) && 
            Objects.equal(this.xProductList, other.xProductList) && 
            Objects.equal(this.useCouponInfoList, other.useCouponInfoList) && 
            Objects.equal(this.usePromotionInfoList, other.usePromotionInfoList) && 
            Objects.equal(this.packageAttachInfoList, other.packageAttachInfoList);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.requestHeader);
        result = 31 * result + Objects.hashCode(this.action);
        result = 31 * result + Objects.hashCode(this.orderID);
        result = 31 * result + Objects.hashCode(this.searchCriteriaToken);
        result = 31 * result + Objects.hashCode(this.routeSearchToken);
        result = 31 * result + Objects.hashCode(this.qteInfo);
        result = 31 * result + Objects.hashCode(this.travelerInfoList);
        result = 31 * result + Objects.hashCode(this.contactInfo);
        result = 31 * result + Objects.hashCode(this.deliveryInfo);
        result = 31 * result + Objects.hashCode(this.paymentInfo);
        result = 31 * result + Objects.hashCode(this.orderMiscInfo);
        result = 31 * result + Objects.hashCode(this.xProductList);
        result = 31 * result + Objects.hashCode(this.useCouponInfoList);
        result = 31 * result + Objects.hashCode(this.usePromotionInfoList);
        result = 31 * result + Objects.hashCode(this.packageAttachInfoList);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("requestHeader", requestHeader)
            .add("action", action)
            .add("orderID", orderID)
            .add("searchCriteriaToken", searchCriteriaToken)
            .add("routeSearchToken", routeSearchToken)
            .add("qteInfo", qteInfo)
            .add("travelerInfoList", travelerInfoList)
            .add("contactInfo", contactInfo)
            .add("deliveryInfo", deliveryInfo)
            .add("paymentInfo", paymentInfo)
            .add("orderMiscInfo", orderMiscInfo)
            .add("xProductList", xProductList)
            .add("useCouponInfoList", useCouponInfoList)
            .add("usePromotionInfoList", usePromotionInfoList)
            .add("packageAttachInfoList", packageAttachInfoList)
            .toString();
    }

}