/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.intlflight.ordering.contract.saveorder.v2;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 经港飞船产品信息
 */
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ShuttleBoatProductInfoType", namespace = "urn:com:ctrip:flight:intl:booking:order:contract:saveorder:v2", propOrder = {
    "voyageCode",
    "seatRankID"
})
@SuppressWarnings("all")
public class ShuttleBoatProductInfoType implements Serializable {

    private static final long serialVersionUID = 1L;

    public ShuttleBoatProductInfoType(
        String voyageCode, 
        String seatRankID) {
        this.voyageCode = voyageCode;
        this.seatRankID = seatRankID;
    }

    public ShuttleBoatProductInfoType() {
    }

    @JsonProperty("VoyageCode")
    @XmlElement(name = "VoyageCode")
    private String voyageCode;

    @JsonProperty("SeatRankID")
    @XmlElement(name = "SeatRankID")
    private String seatRankID;

    /**
     * 班次ID
     */
    public String getVoyageCode() {
        return this.voyageCode;
    }

    public void setVoyageCode(String voyageCode) {
        this.voyageCode = voyageCode;
    }

    /**
     * 座位等级ID
     */
    public String getSeatRankID() {
        return this.seatRankID;
    }

    public void setSeatRankID(String seatRankID) {
        this.seatRankID = seatRankID;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final ShuttleBoatProductInfoType other = (ShuttleBoatProductInfoType)obj;
        return
            Objects.equal(this.voyageCode, other.voyageCode) && 
            Objects.equal(this.seatRankID, other.seatRankID);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.voyageCode);
        result = 31 * result + Objects.hashCode(this.seatRankID);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("voyageCode", voyageCode)
            .add("seatRankID", seatRankID)
            .toString();
    }

}