/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.intlflight.ordering.contract.saveorder.v2;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 经港飞车产品信息
 */
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ShuttleBusProductInfoType", namespace = "urn:com:ctrip:flight:intl:booking:order:contract:saveorder:v2", propOrder = {
    "runID"
})
@SuppressWarnings("all")
public class ShuttleBusProductInfoType implements Serializable {

    private static final long serialVersionUID = 1L;

    public ShuttleBusProductInfoType(
        String runID) {
        this.runID = runID;
    }

    public ShuttleBusProductInfoType() {
    }

    @JsonProperty("RunID")
    @XmlElement(name = "RunID")
    private String runID;

    /**
     * 班次ID
     */
    public String getRunID() {
        return this.runID;
    }

    public void setRunID(String runID) {
        this.runID = runID;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final ShuttleBusProductInfoType other = (ShuttleBusProductInfoType)obj;
        return
            Objects.equal(this.runID, other.runID);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.runID);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("runID", runID)
            .toString();
    }

}