/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.intlflight.ordering.contract.saveorder.v2;

import com.ctrip.intlflight.ordering.contract.commontype.v1.AddressType;
import com.ctrip.intlflight.ordering.contract.commontype.v1.MailingPayTypeType;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.io.Serializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 邮寄行程单PJS,包括邮寄(平邮，挂号信)，第三方快递，EMS
 */
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ThirdPartyDeliveryType", namespace = "urn:com:ctrip:flight:intl:booking:order:contract:saveorder:v2", propOrder = {
    "mailingPayType",
    "deliveryFee",
    "deliveryDateTime",
    "address",
    "personName",
    "mobilePhone",
    "postOrderID",
    "specifiedDeliveryTime",
    "countryCodeForeign",
    "invoiceEmail",
    "expressCompanyID"
})
@SuppressWarnings("all")
public class ThirdPartyDeliveryType implements Serializable {

    private static final long serialVersionUID = 1L;

    public ThirdPartyDeliveryType(
        MailingPayTypeType mailingPayType,
        BigDecimal deliveryFee, 
        String deliveryDateTime, 
        AddressType address,
        String personName, 
        String mobilePhone, 
        long postOrderID, 
        String specifiedDeliveryTime, 
        String countryCodeForeign, 
        String invoiceEmail, 
        long expressCompanyID) {
        this.mailingPayType = mailingPayType;
        this.deliveryFee = deliveryFee;
        this.deliveryDateTime = deliveryDateTime;
        this.address = address;
        this.personName = personName;
        this.mobilePhone = mobilePhone;
        this.postOrderID = postOrderID;
        this.specifiedDeliveryTime = specifiedDeliveryTime;
        this.countryCodeForeign = countryCodeForeign;
        this.invoiceEmail = invoiceEmail;
        this.expressCompanyID = expressCompanyID;
    }

    public ThirdPartyDeliveryType() {
        this.mailingPayType = MailingPayTypeType.values()[0];
        this.deliveryFee = new BigDecimal(0);
    }

    @JsonProperty("MailingPayType")
    @XmlElement(name = "MailingPayType")
    private MailingPayTypeType mailingPayType;

    @JsonProperty("DeliveryFee")
    @XmlElement(name = "DeliveryFee")
    private BigDecimal deliveryFee;

    @JsonProperty("DeliveryDateTime")
    @XmlElement(name = "DeliveryDateTime")
    private String deliveryDateTime;

    @JsonProperty("Address")
    @XmlElement(name = "Address")
    private AddressType address;

    @JsonProperty("PersonName")
    @XmlElement(name = "PersonName")
    private String personName;

    @JsonProperty("MobilePhone")
    @XmlElement(name = "MobilePhone")
    private String mobilePhone;

    @JsonProperty("PostOrderID")
    @XmlElement(name = "PostOrderID")
    private long postOrderID;

    @JsonProperty("SpecifiedDeliveryTime")
    @XmlElement(name = "SpecifiedDeliveryTime")
    private String specifiedDeliveryTime;

    @JsonProperty("CountryCodeForeign")
    @XmlElement(name = "CountryCodeForeign")
    private String countryCodeForeign;

    @JsonProperty("InvoiceEmail")
    @XmlElement(name = "InvoiceEmail")
    private String invoiceEmail;

    @JsonProperty("ExpressCompanyID")
    @XmlElement(name = "ExpressCompanyID")
    private long expressCompanyID;

    /**
     * 快递方式（Normal-普通方式/Integral-积分抵扣/GiftCard-送礼品卡）
     */
    public MailingPayTypeType getMailingPayType() {
        return this.mailingPayType;
    }

    public void setMailingPayType(MailingPayTypeType mailingPayType) {
        this.mailingPayType = mailingPayType;
    }

    /**
     * 快递费/邮寄费
     */
    public BigDecimal getDeliveryFee() {
        return this.deliveryFee;
    }

    public void setDeliveryFee(BigDecimal deliveryFee) {
        this.deliveryFee = deliveryFee;
    }

    /**
     * 最晚配送时间（第三方配送预计送达到客户的时间） yyyy-MM-dd HH:mm:ss
     */
    public String getDeliveryDateTime() {
        return this.deliveryDateTime;
    }

    public void setDeliveryDateTime(String deliveryDateTime) {
        this.deliveryDateTime = deliveryDateTime;
    }

    /**
     * 地址信息
     */
    public AddressType getAddress() {
        return this.address;
    }

    public void setAddress(AddressType address) {
        this.address = address;
    }

    /**
     * 联系人
     */
    public String getPersonName() {
        return this.personName;
    }

    public void setPersonName(String personName) {
        this.personName = personName;
    }

    /**
     * 手机
     */
    public String getMobilePhone() {
        return this.mobilePhone;
    }

    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone;
    }

    /**
     * 合并邮寄主订单号
     */
    public long getPostOrderID() {
        return this.postOrderID;
    }

    public void setPostOrderID(long postOrderID) {
        this.postOrderID = postOrderID;
    }

    /**
     * 指定邮寄时间 yyyy-MM-dd HH:mm:ss
     */
    public String getSpecifiedDeliveryTime() {
        return this.specifiedDeliveryTime;
    }

    public void setSpecifiedDeliveryTime(String specifiedDeliveryTime) {
        this.specifiedDeliveryTime = specifiedDeliveryTime;
    }

    /**
     * 国外国家码(手机)
     */
    public String getCountryCodeForeign() {
        return this.countryCodeForeign;
    }

    public void setCountryCodeForeign(String countryCodeForeign) {
        this.countryCodeForeign = countryCodeForeign;
    }

    /**
     * 报销凭证邮箱
     */
    public String getInvoiceEmail() {
        return this.invoiceEmail;
    }

    public void setInvoiceEmail(String invoiceEmail) {
        this.invoiceEmail = invoiceEmail;
    }

    /**
     * 快递公司ID
     */
    public long getExpressCompanyID() {
        return this.expressCompanyID;
    }

    public void setExpressCompanyID(long expressCompanyID) {
        this.expressCompanyID = expressCompanyID;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final ThirdPartyDeliveryType other = (ThirdPartyDeliveryType)obj;
        return
            Objects.equal(this.mailingPayType, other.mailingPayType) && 
            Objects.equal(this.deliveryFee, other.deliveryFee) && 
            Objects.equal(this.deliveryDateTime, other.deliveryDateTime) && 
            Objects.equal(this.address, other.address) && 
            Objects.equal(this.personName, other.personName) && 
            Objects.equal(this.mobilePhone, other.mobilePhone) && 
            Objects.equal(this.postOrderID, other.postOrderID) && 
            Objects.equal(this.specifiedDeliveryTime, other.specifiedDeliveryTime) && 
            Objects.equal(this.countryCodeForeign, other.countryCodeForeign) && 
            Objects.equal(this.invoiceEmail, other.invoiceEmail) && 
            Objects.equal(this.expressCompanyID, other.expressCompanyID);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.mailingPayType);
        result = 31 * result + Objects.hashCode(this.deliveryFee);
        result = 31 * result + Objects.hashCode(this.deliveryDateTime);
        result = 31 * result + Objects.hashCode(this.address);
        result = 31 * result + Objects.hashCode(this.personName);
        result = 31 * result + Objects.hashCode(this.mobilePhone);
        result = 31 * result + Objects.hashCode(this.postOrderID);
        result = 31 * result + Objects.hashCode(this.specifiedDeliveryTime);
        result = 31 * result + Objects.hashCode(this.countryCodeForeign);
        result = 31 * result + Objects.hashCode(this.invoiceEmail);
        result = 31 * result + Objects.hashCode(this.expressCompanyID);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("mailingPayType", mailingPayType)
            .add("deliveryFee", deliveryFee)
            .add("deliveryDateTime", deliveryDateTime)
            .add("address", address)
            .add("personName", personName)
            .add("mobilePhone", mobilePhone)
            .add("postOrderID", postOrderID)
            .add("specifiedDeliveryTime", specifiedDeliveryTime)
            .add("countryCodeForeign", countryCodeForeign)
            .add("invoiceEmail", invoiceEmail)
            .add("expressCompanyID", expressCompanyID)
            .toString();
    }

}