/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.intlflight.ordering.contract.saveorder.v2;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 使用优惠信息
 */
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UsePromotionInfoType", namespace = "urn:com:ctrip:flight:intl:booking:order:contract:saveorder:v2", propOrder = {
    "referenceID",
    "promotionType",
    "code"
})
@SuppressWarnings("all")
public class UsePromotionInfoType implements Serializable {

    private static final long serialVersionUID = 1L;

    public UsePromotionInfoType(
        String referenceID, 
        String promotionType, 
        String code) {
        this.referenceID = referenceID;
        this.promotionType = promotionType;
        this.code = code;
    }

    public UsePromotionInfoType() {
    }

    @JsonProperty("ReferenceID")
    @XmlElement(name = "ReferenceID")
    private String referenceID;

    @JsonProperty("PromotionType")
    @XmlElement(name = "PromotionType")
    private String promotionType;

    @JsonProperty("Code")
    @XmlElement(name = "Code")
    private String code;

    /**
     * 使用优惠信息ID, 唯一标识符
     */
    public String getReferenceID() {
        return this.referenceID;
    }

    public void setReferenceID(String referenceID) {
        this.referenceID = referenceID;
    }

    /**
     * 优惠类型，传值请严格按照 PromotionTypeEnum 枚举 Name 传值；如使用权益-UseInterests
     */
    public String getPromotionType() {
        return this.promotionType;
    }

    public void setPromotionType(String promotionType) {
        this.promotionType = promotionType;
    }

    /**
     * 优惠码，如使用权益时传权益明细ID
     */
    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final UsePromotionInfoType other = (UsePromotionInfoType)obj;
        return
            Objects.equal(this.referenceID, other.referenceID) && 
            Objects.equal(this.promotionType, other.promotionType) && 
            Objects.equal(this.code, other.code);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.referenceID);
        result = 31 * result + Objects.hashCode(this.promotionType);
        result = 31 * result + Objects.hashCode(this.code);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("referenceID", referenceID)
            .add("promotionType", promotionType)
            .add("code", code)
            .toString();
    }

}