// Generated by eBay Common SDK Platform
package com.ctrip.intlflight.ordering.contract.saveorder.v2;

import com.fasterxml.jackson.annotation.JsonValue;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlEnumValue;

/**
 * 产品类型枚举
 */
@XmlType(name = "XProductTypeEnum")
@XmlEnum
@SuppressWarnings("all")
public enum XProductTypeEnum {

    /**
     * 机票
     */
    @XmlEnumValue("AIR_TICKET")
    AIR_TICKET(0, "AIR_TICKET"),

    /**
     * 巴士
     */
    @XmlEnumValue("BUS")
    BUS(1, "BUS"),

    /**
     * 接送机
     */
    @XmlEnumValue("AIRPORT_TRANSFERS")
    AIRPORT_TRANSFERS(2, "AIRPORT_TRANSFERS"),

    /**
     * 经港飞 船
     */
    @XmlEnumValue("SHUTTLE_BOAT")
    SHUTTLE_BOAT(3, "SHUTTLE_BOAT"),

    /**
     * 经港飞 接驳车
     */
    @XmlEnumValue("SHUTTLE_BUS")
    SHUTTLE_BUS(4, "SHUTTLE_BUS"),

    /**
     * 无线网络
     */
    @XmlEnumValue("WIFI")
    WIFI(5, "WIFI"),

    /**
     * 值机
     */
    @XmlEnumValue("CHECK_IN")
    CHECK_IN(6, "CHECK_IN"),

    /**
     * 休息室
     */
    @XmlEnumValue("LOUNGE")
    LOUNGE(7, "LOUNGE"),

    /**
     * 餐食
     */
    @XmlEnumValue("MEAL")
    MEAL(8, "MEAL"),

    /**
     * 行李额
     */
    @XmlEnumValue("BAGGAGE")
    BAGGAGE(9, "BAGGAGE"),

    /**
     * 促销
     */
    @XmlEnumValue("PROMOTION")
    PROMOTION(10, "PROMOTION"),

    /**
     * 购物优惠券
     */
    @XmlEnumValue("SHOPPING_COUPON")
    SHOPPING_COUPON(11, "SHOPPING_COUPON"),

    /**
     * 签证
     */
    @XmlEnumValue("VISA")
    VISA(12, "VISA"),

    /**
     * 保险
     */
    @XmlEnumValue("INSURANCE")
    INSURANCE(13, "INSURANCE"),

    /**
     * 机+优惠券，举例：接送机、酒店优惠券
     */
    @XmlEnumValue("GIFT_PACKAGE")
    GIFT_PACKAGE(14, "GIFT_PACKAGE"),

    /**
     * 国际金牌服务包
     */
    @XmlEnumValue("SERVICE_PACK")
    SERVICE_PACK(15, "SERVICE_PACK"),

    /**
     * 会员权益
     */
    @XmlEnumValue("AIRLINE_MEMBERSHIP")
    AIRLINE_MEMBERSHIP(16, "AIRLINE_MEMBERSHIP"),

    /**
     * 超级会员
     */
    @XmlEnumValue("INTERESTS")
    INTERESTS(17, "INTERESTS");

    private final int intValue;
    private final String value;

    XProductTypeEnum(int intValue, String value) {
        this.intValue = intValue;
        this.value = value;
    }

    public int getValue() {
        return intValue;
    }

    @JsonValue
    public String value() {
        return value;
    }

    public static XProductTypeEnum fromValue(String v) {
        for (XProductTypeEnum e: XProductTypeEnum.values()) {
            if (e.value.equalsIgnoreCase(v)) {
                return e;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public static XProductTypeEnum findByValue(int value) {
        switch (value) {
            case 0:
                return AIR_TICKET;
            case 1:
                return BUS;
            case 2:
                return AIRPORT_TRANSFERS;
            case 3:
                return SHUTTLE_BOAT;
            case 4:
                return SHUTTLE_BUS;
            case 5:
                return WIFI;
            case 6:
                return CHECK_IN;
            case 7:
                return LOUNGE;
            case 8:
                return MEAL;
            case 9:
                return BAGGAGE;
            case 10:
                return PROMOTION;
            case 11:
                return SHOPPING_COUPON;
            case 12:
                return VISA;
            case 13:
                return INSURANCE;
            case 14:
                return GIFT_PACKAGE;
            case 15:
                return SERVICE_PACK;
            case 16:
                return AIRLINE_MEMBERSHIP;
            case 17:
                return INTERESTS;
            default:
                return null;
        }
    }
}