/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.intlflight.ordering.contract.saveorder.v2;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.io.Serializable;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlType;

/**
 * X 产品信息类型
 */
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XProductInfoType", namespace = "urn:com:ctrip:flight:intl:booking:order:contract:saveorder:v2", propOrder = {
    "xProductType",
    "xProductCommonInfo",
    "xProductTravelerList",
    "xProductExtendInfo"
})
@SuppressWarnings("all")
public class XProductInfoType implements Serializable {

    private static final long serialVersionUID = 1L;

    public XProductInfoType(
        String xProductType, 
        XProductCommonInfoType xProductCommonInfo,
        List<XProductTravelerInfoType> xProductTravelerList,
        XProductExtendInfoType xProductExtendInfo) {
        this.xProductType = xProductType;
        this.xProductCommonInfo = xProductCommonInfo;
        this.xProductTravelerList = xProductTravelerList;
        this.xProductExtendInfo = xProductExtendInfo;
    }

    public XProductInfoType() {
    }

    @JsonProperty("XProductType")
    @XmlElement(name = "XProductType")
    private String xProductType;

    @JsonProperty("XProductCommonInfo")
    @XmlElement(name = "XProductCommonInfo")
    private XProductCommonInfoType xProductCommonInfo;

    @JsonProperty("XProductTravelerList")
    @XmlElement(name = "XProductTravelerInfo")
    @XmlElementWrapper(name = "XProductTravelerList")
    private List<XProductTravelerInfoType> xProductTravelerList;

    @JsonProperty("XProductExtendInfo")
    @XmlElement(name = "XProductExtendInfo")
    private XProductExtendInfoType xProductExtendInfo;

    /**
     * X 产品类型，传值请严格按照 XProductTypeEnum 枚举 Name 传值
     */
    public String getXProductType() {
        return this.xProductType;
    }

    public void setXProductType(String xProductType) {
        this.xProductType = xProductType;
    }

    /**
     * X 产品通用信息
     */
    public XProductCommonInfoType getXProductCommonInfo() {
        return this.xProductCommonInfo;
    }

    public void setXProductCommonInfo(XProductCommonInfoType xProductCommonInfo) {
        this.xProductCommonInfo = xProductCommonInfo;
    }

    /**
     * X 产品乘机人信息集合
     */
    public List<XProductTravelerInfoType> getXProductTravelerList() {
        return this.xProductTravelerList;
    }

    public void setXProductTravelerList(List<XProductTravelerInfoType> xProductTravelerList) {
        this.xProductTravelerList = xProductTravelerList;
    }

    /**
     * X 产品扩展信息集合
     */
    public XProductExtendInfoType getXProductExtendInfo() {
        return this.xProductExtendInfo;
    }

    public void setXProductExtendInfo(XProductExtendInfoType xProductExtendInfo) {
        this.xProductExtendInfo = xProductExtendInfo;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final XProductInfoType other = (XProductInfoType)obj;
        return
            Objects.equal(this.xProductType, other.xProductType) && 
            Objects.equal(this.xProductCommonInfo, other.xProductCommonInfo) && 
            Objects.equal(this.xProductTravelerList, other.xProductTravelerList) && 
            Objects.equal(this.xProductExtendInfo, other.xProductExtendInfo);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.xProductType);
        result = 31 * result + Objects.hashCode(this.xProductCommonInfo);
        result = 31 * result + Objects.hashCode(this.xProductTravelerList);
        result = 31 * result + Objects.hashCode(this.xProductExtendInfo);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("xProductType", xProductType)
            .add("xProductCommonInfo", xProductCommonInfo)
            .add("xProductTravelerList", xProductTravelerList)
            .add("xProductExtendInfo", xProductExtendInfo)
            .toString();
    }

}