/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.intlflight.ordering.contract.saveorder.v2;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XProductFailInfoType", namespace = "urn:com:ctrip:flight:intl:booking:order:contract:saveorder:v2", propOrder = {
    "productType",
    "passengerName",
    "productToken"
})
@SuppressWarnings("all")
public class XProductFailInfoType implements Serializable {

    private static final long serialVersionUID = 1L;

    public XProductFailInfoType(
        String productType, 
        String passengerName, 
        String productToken) {
        this.productType = productType;
        this.passengerName = passengerName;
        this.productToken = productToken;
    }

    public XProductFailInfoType() {
    }

    @JsonProperty("ProductType")
    @XmlElement(name = "ProductType")
    private String productType;

    @JsonProperty("PassengerName")
    @XmlElement(name = "PassengerName")
    private String passengerName;

    @JsonProperty("ProductToken")
    @XmlElement(name = "ProductToken")
    private String productToken;

    /**
     * 产品类型
     */
    public String getProductType() {
        return this.productType;
    }

    public void setProductType(String productType) {
        this.productType = productType;
    }

    /**
     * 购买者乘客姓名
     */
    public String getPassengerName() {
        return this.passengerName;
    }

    public void setPassengerName(String passengerName) {
        this.passengerName = passengerName;
    }

    /**
     * 产品token
     */
    public String getProductToken() {
        return this.productToken;
    }

    public void setProductToken(String productToken) {
        this.productToken = productToken;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final XProductFailInfoType other = (XProductFailInfoType)obj;
        return
            Objects.equal(this.productType, other.productType) && 
            Objects.equal(this.passengerName, other.passengerName) && 
            Objects.equal(this.productToken, other.productToken);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.productType);
        result = 31 * result + Objects.hashCode(this.passengerName);
        result = 31 * result + Objects.hashCode(this.productToken);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("productType", productType)
            .add("passengerName", passengerName)
            .add("productToken", productToken)
            .toString();
    }

}