/**
 * Autogenerated by soa-sdk-toolkit
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ctrip.intlflight.ordering.contract.saveorder.v2;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * X产品扩展信息
 */
@JsonAutoDetect(getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE, isGetterVisibility = Visibility.NONE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XProductExtendInfoType", namespace = "urn:com:ctrip:flight:intl:booking:order:contract:saveorder:v2", propOrder = {
    "checkInInfo",
    "visaProductInfo",
    "insuranceProductInfo",
    "shuttleBoatProductInfo",
    "shuttleBusProductInfo"
})
@SuppressWarnings("all")
public class XProductExtendInfoType implements Serializable {

    private static final long serialVersionUID = 1L;

    public XProductExtendInfoType(
        CheckInInfoType checkInInfo,
        VisaProductInfoType visaProductInfo,
        InsuranceProductInfoType insuranceProductInfo,
        ShuttleBoatProductInfoType shuttleBoatProductInfo,
        ShuttleBusProductInfoType shuttleBusProductInfo) {
        this.checkInInfo = checkInInfo;
        this.visaProductInfo = visaProductInfo;
        this.insuranceProductInfo = insuranceProductInfo;
        this.shuttleBoatProductInfo = shuttleBoatProductInfo;
        this.shuttleBusProductInfo = shuttleBusProductInfo;
    }

    public XProductExtendInfoType() {
    }

    @JsonProperty("CheckInInfo")
    @XmlElement(name = "CheckInInfo")
    private CheckInInfoType checkInInfo;

    @JsonProperty("VisaProductInfo")
    @XmlElement(name = "VisaProductInfo")
    private VisaProductInfoType visaProductInfo;

    @JsonProperty("InsuranceProductInfo")
    @XmlElement(name = "InsuranceProductInfo")
    private InsuranceProductInfoType insuranceProductInfo;

    @JsonProperty("ShuttleBoatProductInfo")
    @XmlElement(name = "ShuttleBoatProductInfo")
    private ShuttleBoatProductInfoType shuttleBoatProductInfo;

    @JsonProperty("ShuttleBusProductInfo")
    @XmlElement(name = "ShuttleBusProductInfo")
    private ShuttleBusProductInfoType shuttleBusProductInfo;

    /**
     * 值机信息
     */
    public CheckInInfoType getCheckInInfo() {
        return this.checkInInfo;
    }

    public void setCheckInInfo(CheckInInfoType checkInInfo) {
        this.checkInInfo = checkInInfo;
    }

    /**
     * 签证产品信息
     */
    public VisaProductInfoType getVisaProductInfo() {
        return this.visaProductInfo;
    }

    public void setVisaProductInfo(VisaProductInfoType visaProductInfo) {
        this.visaProductInfo = visaProductInfo;
    }

    /**
     * 保险产品信息
     */
    public InsuranceProductInfoType getInsuranceProductInfo() {
        return this.insuranceProductInfo;
    }

    public void setInsuranceProductInfo(InsuranceProductInfoType insuranceProductInfo) {
        this.insuranceProductInfo = insuranceProductInfo;
    }

    /**
     * 经港飞船产品信息
     */
    public ShuttleBoatProductInfoType getShuttleBoatProductInfo() {
        return this.shuttleBoatProductInfo;
    }

    public void setShuttleBoatProductInfo(ShuttleBoatProductInfoType shuttleBoatProductInfo) {
        this.shuttleBoatProductInfo = shuttleBoatProductInfo;
    }

    /**
     * 经港飞车产品信息
     */
    public ShuttleBusProductInfoType getShuttleBusProductInfo() {
        return this.shuttleBusProductInfo;
    }

    public void setShuttleBusProductInfo(ShuttleBusProductInfoType shuttleBusProductInfo) {
        this.shuttleBusProductInfo = shuttleBusProductInfo;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        final XProductExtendInfoType other = (XProductExtendInfoType)obj;
        return
            Objects.equal(this.checkInInfo, other.checkInInfo) && 
            Objects.equal(this.visaProductInfo, other.visaProductInfo) && 
            Objects.equal(this.insuranceProductInfo, other.insuranceProductInfo) && 
            Objects.equal(this.shuttleBoatProductInfo, other.shuttleBoatProductInfo) && 
            Objects.equal(this.shuttleBusProductInfo, other.shuttleBusProductInfo);
    }

    @Override
    public int hashCode() {
        int result = 1;

        result = 31 * result + Objects.hashCode(this.checkInInfo);
        result = 31 * result + Objects.hashCode(this.visaProductInfo);
        result = 31 * result + Objects.hashCode(this.insuranceProductInfo);
        result = 31 * result + Objects.hashCode(this.shuttleBoatProductInfo);
        result = 31 * result + Objects.hashCode(this.shuttleBusProductInfo);

        return result;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
            .add("checkInInfo", checkInInfo)
            .add("visaProductInfo", visaProductInfo)
            .add("insuranceProductInfo", insuranceProductInfo)
            .add("shuttleBoatProductInfo", shuttleBoatProductInfo)
            .add("shuttleBusProductInfo", shuttleBusProductInfo)
            .toString();
    }

}